### ISSUE TITLE
当前版本安装 首选项黑屏

### ISSUE THREAD

**Issue by ChinJCheung** [volatile-static/Chartero#1]
当前版本安装首选项黑屏，请问可以是否新版本吗

**Comment by llity** [comment]
> 你好，目前在mac OS上是这样的，并且暂时无法修复，请等待zotero7发布。Windows与Linux不存在这个问题。

zotero 6 好像没发布多久呢，7得等很久

**Comment by volatile-static** [comment]
@llity beta版出了一个月了

**Comment by llity** [comment]
@volatile-static 看今年能正式版吗？期待很久的metadata update，很多年了没有合并。

**Comment by volatile-static** [comment]
正式版可能还有一两个月，metadata update我不了解

**Comment by llity** [comment]
@volatile-static 那比较快。有个极大的担心，火狐现状的市场占有率很低。zotero基于FF的内核开发，真怕FF哪天倒下。

**Comment by volatile-static** [comment]
不出意外的话应该是没问题了
