### ISSUE TITLE
想问一下“读完的文献”判定标准和“挂机提醒”的判定标准

### ISSUE THREAD

**Issue by jiuwu-zzx** [volatile-static/Chartero#106]
![image](https://github.com/volatile-static/Chartero/assets/75843496/57b5f162-fb7b-45c9-adf3-71720402adae)
首先感谢作者大大，如题，我刚开始用这个插件，有些文献我看完了，但是侧边栏没有显示，我想问一下这个判定标准是什么。

除此之外，挂机的时候有红框提醒，有的地方我确实需要读很久，但似乎移动鼠标没啥用，得移动页面，而且回到原页面后不一会儿又开始提醒？我不太清楚，所以想咨询一下。

谢谢作者

**Comment by volatile-static** [comment]
首先提醒你一下，style和chartero的记录是互不兼容的，你要区分哪些是style的功能。
然后这些问题其实我也很难解释清楚，只能说你用多了就找到规律了哈哈。建议你过几天再想想还有什么问题

**Comment by jiuwu-zzx** [comment]
> 首先提醒你一下，style和chartero的记录是互不兼容的，你要区分哪些是style的功能。 然后这些问题其实我也很难解释清楚，只能说你用多了就找到规律了哈哈。建议你过几天再想想还有什么问题

 好嘞，谢谢，那我再感受感受
