### ISSUE TITLE
Chartero点击图表识别功能一直显示加载更多

### ISSUE THREAD

**Issue by woodGHub** [volatile-static/Chartero#111]
Chartero点击图表识别功能一直显示加载更多
![image](https://github.com/volatile-static/Chartero/assets/44263447/788a25ea-84ca-4e39-8f13-f5d2eb2eb1cb)
版本：2.7.1；
![image](https://github.com/volatile-static/Chartero/assets/44263447/3c1417a8-9acf-4dfc-9d70-16bdde8ee4d4)

**Comment by volatile-static** [comment]
如果很长时间都没有更多图片出现的话一般就是加载完成了，手动关闭弹窗即可

**Comment by woodGHub** [comment]
> 如果很长时间都没有更多图片出现的话一般就是加载完成了，手动关闭弹窗即可
关键是图片没有出来呀？
![image](https://github.com/volatile-static/Chartero/assets/44263447/45b48193-0992-4882-bac0-33af611b4d8d)

**Comment by volatile-static** [comment]
你看的是扫描版pdf吧

**Comment by woodGHub** [comment]
> 你看的是扫描版pdf吧

不是扫描的也不行，pdf figure能识别图片的pdf文档，chartero也不行

**Comment by volatile-static** [comment]
你找一篇这样的文档发我试一下


> 不是扫描的也不行，pdf figure能识别图片的pdf文档，chartero也不行

**Comment by volatile-static** [comment]
这是最近更新后出现的问题吧

**Comment by woodGHub** [comment]
> 这是最近更新后出现的问题吧

是的是的
