### ISSUE TITLE
请问哪个版本适用mac版 zotero 6.0.37？

### ISSUE THREAD

**Issue by goododo** [volatile-static/Chartero#118]
您好，谢谢您开发这个功能强大的插件。但我尝试安装了一些版本的Chartero，但一直显示installation failed，“The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.” 请问哪个版本的Chartero我可以用于这个版本的zotero呢？

**Comment by volatile-static** [comment]
https://github.com/volatile-static/Chartero/releases/tag/1.3.3
