### ISSUE TITLE
有一个chartero自动生成的“阅读历史记录”问题，

### ISSUE THREAD

**Issue by Marshal-Duan** [volatile-static/Chartero#119]
mac版本中，zotero7，chartero也是2.9.3，在阅读历史记录中的笔记会在所有笔记中显示，但是同样地，在同步的win电脑上就不显示，请问如何把mac上自动生成的阅读历史记录的笔记隐藏掉呢？

**Comment by Marshal-Duan** [comment]
![Uploading 图片_20240809102338.jpg…]()

**Comment by Marshal-Duan** [comment]
![图片_20240809102338](https://github.com/user-attachments/assets/71316af1-de38-4246-880e-6ee6e6f293e6)
![图片_20240809102343](https://github.com/user-attachments/assets/b638880a-2154-4316-b295-03324d7c5260)

**Comment by volatile-static** [comment]
手头没Mac电脑，晚点再解决这个问题

**Comment by volatile-static** [comment]
我这边mac上不显示的。可能是你那台电脑没有正常识别到记录

**Comment by volatile-static** [comment]
看到你mac截图上是没有chartero的，所以不会隐藏这些笔记

**Comment by Marshal-Duan** [comment]
> 看到你mac截图上是没有chartero的，所以不会隐藏这些笔记

现在更新了没有这个了，谢谢你啦

**Comment by Marshal-Duan** [comment]
> 看到你mac截图上是没有chartero的，所以不会隐藏这些笔记

是有chartero的，功能也是正常的，只是在没有选中文献的时候，右边没有显示chartero那个按键的。现在更新了之后这个问题就没有了
