### ISSUE TITLE
安装插件后没有识别图片的功能

### ISSUE THREAD

**Issue by zaizhe** [volatile-static/Chartero#12]
RT

**Comment by volatile-static** [comment]
你好，本插件不识别图片，只是把图片搬运到侧边栏。如果文档本身是扫描版，则每页为一个图片，如果文档中全是svg则提取不到。

**Comment by zaizhe** [comment]
DL好，但是我没有#6中的提问者 https://github.com/volatile-static/Chartero/issues/6#issuecomment-1284914687 描述的那个图片的按钮，只有另外三个按钮

**Comment by volatile-static** [comment]
切换到其他标签页再切换回来试一下

**Comment by zaizhe** [comment]
还是没有，重新安装插件后也没有

**Comment by zaizhe** [comment]
还是没有，重新安装插件后也没有

**Comment by volatile-static** [comment]
麻烦你禁用其他插件再试一次，若还没有，请截图zotero插件页面发上来

**Comment by zaizhe** [comment]
还是不行

**Comment by zaizhe** [comment]
怎么添加图片

**Comment by zaizhe** [comment]
![Uploading Snipaste_2022-10-22_16-34-02.jpg…]()

**Comment by zaizhe** [comment]
https://disk.pku.edu.cn:443/link/EE05374FED4534E7575561FF69BE87A3
有效期限：2022-11-20 23:59

**Comment by zaizhe** [comment]
![Snipaste_2022-10-22_16-34-02](https://user-images.githubusercontent.com/47073631/197329901-7069549a-19d4-46c2-ac01-1b1df96cb6cc.jpg)

**Comment by volatile-static** [comment]
检查你安装的版本

**Comment by zaizhe** [comment]
最新版本

**Comment by zaizhe** [comment]
[Chartero(rename zip to xpi).zip](https://github.com/volatile-static/Chartero/files/9843906/Chartero.rename.zip.to.xpi.zip)

**Comment by zaizhe** [comment]
https://github.com/volatile-static/Chartero/releases/download/1.1.1/Chartero.xpi

**Comment by volatile-static** [comment]
语言改为中文

**Comment by zaizhe** [comment]
emmm 这个不能改:)

**Comment by volatile-static** [comment]
你好，感谢配合，错误已修复，新版今晚发布
