### ISSUE TITLE
侧边栏提取图片的问题

### ISSUE THREAD

**Issue by kjoying** [volatile-static/Chartero#120]
发现了几个问题：
• 提取的图片是上下颠倒的
下面这两个是右下角一直显示‘加载更多’，图片提取完了也没显示‘图片加载完成’，可能是这个原因导致的错误
• 提取图片后，点击图片跳转的页面是错的
• 从提取页面切换到其他栏，比如‘’显示缩略图‘’，之后提取图片的按钮会无法点击

**Comment by kjoying** [comment]
![颠倒的图片](https://github.com/user-attachments/assets/762fb000-5540-4c7d-bb65-8128a518e6d3)
![后两个问题](https://github.com/user-attachments/assets/3212e49f-01e3-4227-b52c-a9b272991e65)

**Comment by volatile-static** [comment]
知网的学位论文跟其他的不一样，我也没办法
