### ISSUE TITLE
Chartero version 2.9.3 in Zotero 7.0 64-bit cannot import legacy history or import pasted history

### ISSUE THREAD

**Issue by thunderstudying** [volatile-static/Chartero#124]
Error information of the Chartero 2.9.3 when using the buttons `Automatically search and import legacy history` and `Import pasted history`.
![image](https://github.com/user-attachments/assets/e941852a-f509-4812-9b60-e4caf851483d)
![image](https://github.com/user-attachments/assets/1ecb8ebf-f39f-456f-a875-afea5336fc08)

I have tried other earlier versions, but get the same error (cannot open Chartero settings) as described in https://github.com/volatile-static/Chartero/issues/116.

Thanks for your time.

**Comment by volatile-static** [comment]
#123
