### ISSUE TITLE
Display issues related to book types

### ISSUE THREAD

**Issue by z-zane** [volatile-static/Chartero#129]
There may be some problems with the Chartero dashboard when reading the book. It doesn't show the progress and timeline as shown in the following photo.
![image](https://github.com/user-attachments/assets/5032eced-4a6c-4439-ab3d-5e328945d5cf)

**Comment by volatile-static** [comment]
- [ ] What's your plugin version?
- [ ] Check the related note of this pdf

**Comment by z-zane** [comment]
My plugin version is the latest. And after my trial and looking up other issues, I think it is caused by my action of taking notes that I do not click the pdf again ( I do not set alert when record stops ).
And I have another question, how long will the record timeout setting be better?

**Comment by volatile-static** [comment]
good
The setting depends on the user. In most cases, I guess, default is fine.

**Comment by z-zane** [comment]
OK, I see. Thank you for your response! 
Thank you for your efforts in developing this plugin.
