### ISSUE TITLE
zotero语言设置为英文时，右键菜单不显示“设置chartero历史记录”选项

### ISSUE THREAD

**Issue by mforevery** [volatile-static/Chartero#13]
修改语言为中文时，则一切正常

**Comment by volatile-static** [comment]
你好，请检查是否为最新版

**Comment by mforevery** [comment]
chartero版本号1.1.1
zotero 版本号 6.0.15
zotero语言设置为English时，整个历史记录的文件也会显示为json格式的内容，而不是像中文模式下显示为一个个文献条目

**Comment by volatile-static** [comment]
请更新至1.2.0，如果还有问题可以重新打开本issue，谢谢
