### ISSUE TITLE
希望能增加数据导出的功能

### ISSUE THREAD

**Issue by Dumail** [volatile-static/Chartero#130]
插件记录阅读时间的功能很棒！但可能受限于zotero，在可视化方面还存在一些限制。希望能增加导出数据的功能（例如json），以便通过外部程序（例如Granafa）进行自定义地显示。
目前找到的阅读数据强行导出后仅有zotero中的内部Item编号，例如：
```json
  "#2AHK79PE": {
    "pages": {
      "0": {
        "p": {
          "1701395762": 60,
          "1701395841": 20,
          "1701395900": 30,
          "1701396950": 170,
          "1701397140": 360,
          "1701397510": 30,
          "1701398748": 10
        }
      },
      "1": {
        "p": {
          "1701397540": 240,
          "1701397786": 10
        }
      },
    "numPages": 11
  },
```
导出的数据如果能包含更多的信息就好了，例如标题和作者之类的。似乎在zotero外很难将这些信息与数据中的Item ID进行匹配。

**Comment by volatile-static** [comment]
这种需求似乎涉及数据库或脚本编程？目前没有足够的需求来专门为第三方应用导出特定的格式，建议你借助zotero本地api实现自定义程序

**Comment by Dumail** [comment]
请问在zotero外部能否有办法获取item ID对应的信息呢，在zotero中进行会让工作流变得太复杂

**Comment by volatile-static** [comment]
https://groups.google.com/g/zotero-dev/c/ElvHhIFAXrY/m/fA7SKKwsAgAJ
