### ISSUE TITLE
侧边栏无法正常显示

### ISSUE THREAD

**Issue by stdAri** [volatile-static/Chartero#132]
![image](https://github.com/user-attachments/assets/75eb712c-3ec8-43b5-b0ec-9e2ca353121a)
![image](https://github.com/user-attachments/assets/706067e1-b0ff-4f29-a90c-ca60adc00db6)
![image](https://github.com/user-attachments/assets/bd9181d7-a5d8-4898-9afa-e5c190e3191a)
![image](https://github.com/user-attachments/assets/991756cf-a6e4-4f91-9096-e9387622fd24)
插件好像能正常工作，也能正常记录时间变化，但是无论那个视图下面，都没办法看到阅读进度

**Comment by volatile-static** [comment]
给出版本号。关闭其他所有插件后再试

**Comment by volatile-static** [comment]
zotero的版本呢？

**Comment by stdAri** [comment]
7.0.10 (64-bit)
