### ISSUE TITLE
mac版本在文献库界面不显示

### ISSUE THREAD

**Issue by mosueason** [volatile-static/Chartero#135]
![1733823007859](https://github.com/user-attachments/assets/c06c52a0-d7c5-4063-9316-a893c5c05156)

**Comment by volatile-static** [comment]
Windows没发现异常，其他mac用户有同样的问题吗？

**Comment by volatile-static** [comment]
#136 应该没问题了吧？有的话请重新打开这个issue

**Comment by mosueason** [comment]
> #136 应该没问题了吧？有的话请重新打开这个issue

没问题了！非常感谢！！！
