### ISSUE TITLE
mac电脑有library overview，但是在win电脑里面的查看目录下面没有类似的查看的地方

### ISSUE THREAD

**Issue by restrained-sober** [volatile-static/Chartero#136]
![image](https://github.com/user-attachments/assets/55e1540d-4abf-4694-8f7c-301a509a115b)

**Comment by restrained-sober** [comment]
![image](https://github.com/user-attachments/assets/33544a6e-06d3-4000-9b8c-dcedd2d0d3fc)
评论区展示的是mac电脑的版本，前面发的是win电脑的版本

**Comment by volatile-static** [comment]
#135 你们咋正好相反啊？
mac和win的客户端分别是什么版本？

**Comment by restrained-sober** [comment]
![image](https://github.com/user-attachments/assets/9b0a302a-3d54-4440-bca9-f4b4a528238a)
上面这张图是win客户端的版本号

**Comment by volatile-static** [comment]
该升级了

**Comment by restrained-sober** [comment]
![image](https://github.com/user-attachments/assets/e29a7847-e4ba-4f21-9681-1a260c4bc4a1)
这个是mac电脑客户端的版本号

**Comment by restrained-sober** [comment]
> 该升级了

哈哈哈哈，没想到啊，升级一下就有了，看来是我疏于更新，感谢感谢
