### ISSUE TITLE
Chartero doesn't load under English interface

### ISSUE THREAD

**Issue by chaozg** [volatile-static/Chartero#17]
Hi there,

Thanks very much for the very useful plugin.
I just want to report that Chartero can't load on my Linux machine, if I use zotero under the English interface; Everything works perfectly if zotero is set to Chinese. I'm not sure if anyone else meets the same situation.

Regards,

(I'm posting in English simply in the hope that Chartero will reach a broader international community)

**Comment by volatile-static** [comment]
Chartero was tested in Ubuntu and Mac OS, both Chinese and English were working well. Please reopen this issue if you have further questions, thanks.
