### ISSUE TITLE
能否体现一下相互关联的文献？？？文献图谱

### ISSUE THREAD

**Issue by 1067237855** [volatile-static/Chartero#2]
zotero的“关联文献”功能太难用了，希望出一个文献图谱功能

**Comment by volatile-static** [comment]
已计划

**Comment by volatile-static** [comment]
已实现

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/197344851-787cffd6-87aa-4b7e-bf81-9a60920ef2d0.png)
太棒了，大佬太牛了🐂🍺，效率！！！
几个期待的功能建议：
1.手动连接气泡，从而关联文献。如果不好实现的话，以其他方式实现文献快速关联也可以。（主要目的是希望快速关联文献）
2.跳转或打开气泡对应的文献条目或者PDF（主要目的是希望实现快速定位  相互关联的文献）
3.在仪表盘显示文献图谱
只是一些个人的想法，现在才刚开始，非常期待该功能未来的样子，期待大佬早日优化

![image](https://user-images.githubusercontent.com/104330036/197346195-ba0a5927-7839-41d8-8d1c-f9850fea183b.png)

**Comment by volatile-static** [comment]
你好，感谢建议。你可以暂时通过点击下面图注来调整显示布局

**Comment by volatile-static** [comment]
@1067237855 此外，看到你的图片中彩色节点似乎没有连线，请问这些条目的标签有多少？请拖动节点来确认是否所有彩色节点都没有连线

**Comment by 1067237855** [comment]
> 

大佬有交流群吗？可否加一下，细聊

**Comment by volatile-static** [comment]
+qq：1043064987

**Comment by volatile-static** [comment]
@1067237855 跳转已实现，明天发布。仪表盘功能已列入[todo](https://github.com/volatile-static/Chartero#features).
