### ISSUE TITLE
不兼容的记录格式，请前往数据可视化页面清理！

### ISSUE THREAD

**Issue by hubery055** [volatile-static/Chartero#20]
之前安装过Chartero，但是后来因为某些原因卸载了。重新安装之后，按照要求恢复了之前的Chartero的笔记文件，显示这条错误。去可视化页面清理，依然报错。卸载重装也不能解决这个问题，请问如何才能彻底清理残留文件，谢谢。

**Comment by volatile-static** [comment]
新建笔记，输入`{}`，然后重新设置

**Comment by yuzixieshouhuajiaqi** [comment]
我刚安装，没卸载过，也遇到了同样的问题，新建笔记后，笔记里输入{}，然后笔记设置为[Chartero]历史记录，还是出现此错误提示，请问如何解决

**Comment by lijunweng00** [comment]
> 不兼容的记录格式，请前往数据可视化页面清理
zotero 卸载，所有插件重装，一开始还好没出现，几篇文献读完后，就又出来了

**Comment by volatile-static** [comment]
https://gitee.com/const_volatile/chartero/issues?assignee_id=&author_id=&branch=&collaborator_ids=&issue_search=&label_ids=180755057&label_text=faq&milestone_id=&priority=&private_issue=&program_id=&project_id=const_volatile%2Fchartero&project_type=&scope=&single_label_id=&single_label_text=&sort=&state=closed&target_project=

@lijunweng00 @yuzixieshouhuajiaqi

**Comment by yuzixieshouhuajiaqi** [comment]
> https://gitee.com/const_volatile/chartero/issues/I5Z8CE
> 
> @lijunweng00 @yuzixieshouhuajiaqi

在提此问题之前，我已经尝试过清除无效记录的方法，同样不起作用

**Comment by volatile-static** [comment]
@yuzixieshouhuajiaqi 把你的记录复制到vscode或者其他能编辑json的工具中看一下是否有语法错误

**Comment by yuzixieshouhuajiaqi** [comment]
只有仪表盘正常显示，只要点文库总览就会出现错误提示
![image](https://user-images.githubusercontent.com/76084234/199872542-3207f0f4-9224-4a5b-a36c-8151323b0d9d.png)

**Comment by yuzixieshouhuajiaqi** [comment]
我不是这个专业的，请问你说的这个记录在哪，怎么复制

**Comment by yuzixieshouhuajiaqi** [comment]
![image](https://user-images.githubusercontent.com/76084234/199872996-48dddf84-0ce5-46d5-8658-19f0489dd202.png)
点了复制，内容是空白的

**Comment by volatile-static** [comment]
> 我不是这个专业的，请问你说的这个记录在哪，怎么复制

可以先新建一个正常的，后续会优化数据导出的接口，届时再把你旧的数据导入即可

**Comment by yuzixieshouhuajiaqi** [comment]
您说的新建正常的什么意思，无论新建条目，或者新建子笔记，都会出现此错误提示

**Comment by yuzixieshouhuajiaqi** [comment]
请问在将笔记设置为[Chartero]历史记录之前，Chartero的数据在哪存储

**Comment by volatile-static** [comment]
> 请问在将笔记设置为[Chartero]历史记录之前，Chartero的数据在哪存储

在内存中。



> 您说的新建正常的什么意思，无论新建条目，或者新建子笔记，都会出现此错误提示

1. 新建笔记（是否独立无所谓）
2. 输入`{}`
3. 右键设为历史记录
4. 同步并重启zotero
5. 打开任意pdf阅读并等待记录保存
6. 若此时看到仪表盘正常则一切正常

**Comment by yuzixieshouhuajiaqi** [comment]
按照您的方法我重新操作了一边，还是同样问题，仪表盘从提问之前就一直是正常的，只有文库总览显示不正常
![image](https://user-images.githubusercontent.com/76084234/199875498-579ce374-0beb-4007-bf4c-38422ad5f129.png)

**Comment by volatile-static** [comment]
再重启zotero然后去复制，发上来

**Comment by yuzixieshouhuajiaqi** [comment]
第一次重启后还是同样问题，过了一会，第二次重启后，文库总览完全正常了，感谢~

**Comment by volatile-static** [comment]
能用就行哎😔

**Comment by fyfy6** [comment]
![image](https://user-images.githubusercontent.com/97269052/200113744-b8acc1ce-a0c6-4f5a-ab5a-5919f5713301.png)

**Comment by volatile-static** [comment]
@fyfy6 你看一下readme里的b站视频和faq吧，不然但凭这张图也帮不了你什么

**Comment by fyfy6** [comment]
感谢你的及时回复。我这边的问题是，可以看到仪表盘数据（图1），点击——文库总览（图2），文库总览显示不兼容格式（图3 ）。


我下午在b站查了这个问题，没有看到解决方案，于是去了github咨询。刚开始安装时使用正常，今天出现了问题。


我非常喜欢你们开发的chartero，chartero让我觉得阅读文献这件事变得有趣！希望你能帮我解决这个问题，十分感谢。





















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "volatile-static/Chartero"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月5日(星期六) 晚上7:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [volatile-static/Chartero] 不兼容的记录格式，请前往数据可视化页面清理！ (Issue #20)





 
@fyfy6 你看一下readme里的b站视频和faq吧，不然但凭这张图也帮不了你什么

**Comment by volatile-static** [comment]
@fyfy6 看不到你的回复呀？去gitee提问吧

**Comment by fyfy6** [comment]
下午仪表盘显示记录，文库总览显示不兼容。刚才电脑重启，zotero卸载chartero重新安装，现在仪表盘记录没有，文库总览还是显示不兼容。😫

**Comment by fyfy6** [comment]
我......我......我又来了😅。再次重启后显示正常，但是之前的阅读记录没有了。可以找回嘛

**Comment by volatile-static** [comment]
> 

找到之前的笔记条目（可能在回收站），双击打开全选复制，到当前记录的条目侧边栏右上角有导入json，粘贴进去就好 @fyfy6

**Comment by fyfy6** [comment]
> 
我的回收站是空的😖。谢谢，我很喜欢chartero

**Comment by volatile-static** [comment]
> > 
> 
> 我的回收站是空的😖。谢谢，我很喜欢chartero
@fyfy6 
如果觉得之前的记录很重要，可以尝试以下步骤：
1. 找到zotero数据库文件`zotero.sqlite`
2. 他下面会有同名的.bak文件作为备份，交换二者文件名
3. 断网后重启zotero，找到之前的记录复制到外面
4. 换回两个数据库文件
5. 重启zotero进行同步
6. 导入刚复制的记录
