### ISSUE TITLE
产生的笔记条目太长影响zotero同步

### ISSUE THREAD

**Issue by huphGit** [volatile-static/Chartero#21]
Chartero条目下产生的笔记条目太长影响zotero同步。zotero报错内容如下：
> 注释“{"lib":1,"items":{"7MGR5FZ9":{"n":41,"p"…”太长，无法同步。 缩短便笺并再次同步。
请问作者有没有办法解决？

**Comment by volatile-static** [comment]
你看的太多了，佩服。请你把记录复制到记事本看一下大小告诉我吧

**Comment by huphGit** [comment]
您好！复制到记事本大小500 KB 。我用您这个插件可能用了才不到一个月时间，我感觉看的并不多，可能看了一些书籍页数比较多。

**Comment by volatile-static** [comment]
谢谢。我先想想办法

**Comment by huphGit** [comment]
好的，感谢！

**Comment by GFDGIT** [comment]
要不参考一下ZoteroStyle的实现，就是每个条目记录一个笔记。
![ZoteroStyle](https://user-images.githubusercontent.com/51939531/205325876-28774410-6e22-4a8c-bc91-2bb5029579f7.png)

**Comment by volatile-static** [comment]
@GFDGIT 感想建议！顺便想征求大家的意见：条目的记录数据是集中到Chartero条目下还是分散到各自条目下比较好？
若记录过多，集中的方式可能也会有一定的问题，但分散后会不会影响日常使用体验？

**Comment by GFDGIT** [comment]
分散到各条目下我能想到的好处是，阅读记录可以随条目进行删除移动，如果能和ZoteroStyle统一记录格式，那还能有更好的兼容性。可能缓解同步冲突问题。

坏处是每个条目下多一个进度笔记，无法直接通过是否存在笔记来筛选条目了，可以通过给进度笔记一个明显的标识符，利用高级搜索排除记录笔记实现了，但确实没那么方便了。还有就是进行文库总览时，需要扫描整个库的条目了，不清楚有什么影响。

似乎还是集中会好一点？除了Chartero条目下有很多进度笔记，不会有什么其他问题吧？笔记数量太多会影响同步？

**Comment by volatile-static** [comment]
你说的很有道理，我会优先考虑集中存放

**Comment by wm-Githuber** [comment]
开发者您好，我之前刷新进度条后会显示每篇论文的阅读进度，现在不确定是不是bug了，刷新后不再出现每篇论文的阅读进度，论文的题目呈现不同程度的色彩掩盖。和上面“GFDGIT”用户的情况相似，但是文库总览功能正常使用。
![temp](https://user-images.githubusercontent.com/66511993/205920877-cb490331-e5bc-4e1c-8e1c-0c4a7d6377d1.png)

**Comment by wm-Githuber** [comment]
> 

太妙了！谢谢您的解惑。

**Comment by etShaw-zh** [comment]
可否也考虑使用sqlite存储数据呀？

**Comment by volatile-static** [comment]
> 可否也考虑使用sqlite存储数据呀？

不好意思，我只会前端，不会数据库

**Comment by etShaw-zh** [comment]
>不好意思，我只会前端，不会数据库

@volatile-static  插件已经做得非常棒啦。这里有一些数据库的操作示例，希望对你有帮助 [A Sample Zotero Plugin](https://github.com/volatile-static/Chartero/issues/21#issuecomment-1372117000)

**Comment by volatile-static** [comment]
@etShaw-zh 谢谢你的建议，我简单看了一下，这些数据库语句我都需要从新学，而且新建的sqlite文件不能随zotero数据库自动同步。具体方案我还要再考虑考虑。

**Comment by volatile-static** [comment]
新版本已经解决了。目前zotero7可用
