### ISSUE TITLE
1.3.1“努力画图中”bug

### ISSUE THREAD

**Issue by Tobeprmn** [volatile-static/Chartero#22]
点击“文库总览”，一直显示“努力画图中”，卡片加载不出来。
![image](https://user-images.githubusercontent.com/119318291/205623907-155e77ae-b8d7-4c2a-ada0-80cc5893a199.png)

**Comment by volatile-static** [comment]
已在下个版本修复

**Comment by Tobeprmn** [comment]
感谢！




2249532415
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "volatile-static/Chartero"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 晚上8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [volatile-static/Chartero] 1.3.1“努力画图中”bug (Issue #22)





 
已在下个版本修复
