### ISSUE TITLE
“文库总览”功能卡死情况

### ISSUE THREAD

**Issue by wudidingdong** [volatile-static/Chartero#25]
在12月6日自动更新插件版本后，点击右上角小图标——文库总览，会出现“正在努力画图”字样，随后一直处于卡死状态，重启、关闭再开、放置半小时不管等方法都试过了，依然如此，不过不影响整体使用。
![1670474186193](https://user-images.githubusercontent.com/40603060/206357602-3c30506c-73b2-4e77-944e-6d880a8c75fc.jpg)

**Comment by volatile-static** [comment]
你好，请更新至1.3.2
