### ISSUE TITLE
【bug report】no json generate when install the latest plugin to date for the first time 

### ISSUE THREAD

**Issue by Ravenclawer** [volatile-static/Chartero#28]

**Comment by Ravenclawer** [comment]
![image](https://user-images.githubusercontent.com/73892411/206812007-10728dce-700d-4dcc-86a8-2e58bf4b98db.png)
第一次装这个插件，不知道是不是新版本默认是已经装了旧版本还是其他原因，没有在条目下创建json文件，导致插件不可用，自己随便创建笔记条目后指定为数据文件也没用
![image](https://user-images.githubusercontent.com/73892411/206812502-26bf7178-5371-4280-8a8e-5ba59fe83d79.png)

**Comment by volatile-static** [comment]
阅读后会自动生成的

**Comment by volatile-static** [comment]
如果还有问题，可以重新打开issue
