### ISSUE TITLE
Reading progress not showing in synchronized computers

### ISSUE THREAD

**Issue by atmomomo** [volatile-static/Chartero#29]
Chartero worked well in my office computer. However, the reading progress was now showing in another synchronized computer (nevertheless, I could find the synchronized Chartero json files in the library). 
But when I read a new item in the new computer, the progress did show properly.
Did I miss something? Is there any way to fix? Many thanks!

**Comment by volatile-static** [comment]
When you sync in a new computer, you should find your previous json item in library and right-click to set as history.

**Comment by atmomomo** [comment]
Worked like a charm. Thank you!
