### ISSUE TITLE
每隔几分钟就出现同步问题

### ISSUE THREAD

**Issue by 1067237855** [volatile-static/Chartero#3]
每隔几分钟就出现同步问题

![image](https://user-images.githubusercontent.com/104330036/196208905-4ac13d44-eec2-4e18-9ca6-4d7e9da484f5.png)

**Comment by volatile-static** [comment]
请问你是两台电脑同时在用zotero吗？

**Comment by volatile-static** [comment]
选择本地，然后点finish

**Comment by 1067237855** [comment]
不管用

![image](https://user-images.githubusercontent.com/104330036/196408115-c230583d-bebc-4d27-97a7-e6a02c5f4e6f.png)

**Comment by volatile-static** [comment]
估计是你坚果云把zotero数据库也同步了

**Comment by volatile-static** [comment]
如果还有问题，可以重新打开这个issue
