### ISSUE TITLE
小bug及小建议

### ISSUE THREAD

**Issue by xiaojianjian-huang** [volatile-static/Chartero#31]
开发者您好，您开发的插件我很喜欢，并且很有意义！以下是一些小bug或者小建议，希望能够采纳：
1.存在某些地方的汉化不好；
<img width="529" alt="微信截图_20221210002823" src="https://user-images.githubusercontent.com/71034510/210178748-5f11dc58-00ee-4ade-88df-45f37f78fb47.png">

<img width="454" alt="微信截图_20221210003138" src="https://user-images.githubusercontent.com/71034510/210178756-c948df3b-9818-4e0e-891b-2e5b203bf594.png">

<img width="526" alt="微信截图_20230102005631" src="https://user-images.githubusercontent.com/71034510/210178771-2e9dd320-bbb1-4989-9dce-0e13687160ea.png">

<img width="461" alt="微信截图_20230102004904" src="https://user-images.githubusercontent.com/71034510/210178779-2c585e00-e2c0-4aeb-882a-29c200a8e9e4.png">

<img width="449" alt="微信截图_20230102005303" src="https://user-images.githubusercontent.com/71034510/210178791-a9095ed9-a54a-4adf-aa36-43f212c868b7.png">

2.如果没有阅读的分类，希望不要显示出来；
<img width="454" alt="微信截图_20221210003138" src="https://user-images.githubusercontent.com/71034510/210178811-dd7a40ca-f9b5-46dd-9c90-9d5dee6691aa.png">

3.希望时间统计可以换个单位，秒数统计给别人的感觉并不直观；可以采用双纵坐标的形式，如果是每一天的统计的话，可以以时为单位，如果每小时的统计数据的话可以以分为单位。
<img width="456" alt="微信截图_20230102004809" src="https://user-images.githubusercontent.com/71034510/210178815-86ada8a8-7acf-4df2-b1f2-30bf94c87451.png">

<img width="462" alt="微信截图_20221210003801" src="https://user-images.githubusercontent.com/71034510/210178841-f2c5cb6b-85d2-42ed-906c-251da2c04aa0.png">

<img width="462" alt="微信截图_20221210003836" src="https://user-images.githubusercontent.com/71034510/210178847-d009d645-627b-423c-8171-960579ed5e93.png">

4.希望在不同设备上面的插件可以读取同一个数据统计文件，目前是虽然把数据文件同步过去之后，但在另外一个设备上是读取不了数据的。（之后版本可以提供两个数据文件的合并功能。）
<img width="846" alt="微信截图_20230102010220" src="https://user-images.githubusercontent.com/71034510/210179006-e3c988cf-6b60-430f-816f-8680405fd3d4.png">

<img width="851" alt="微信截图_20230102010345" src="https://user-images.githubusercontent.com/71034510/210179014-43bf0064-411b-4d37-b5fd-ae50b25f88ac.png">

**Comment by volatile-static** [comment]
你好，非常感谢你的建议！首先，对于第四点，请你仔细阅读[readme](https://github.com/volatile-static/Chartero/tree/js_overlay#faq)中的说明，是可以做到多设备同步的。其次，对于第三点，目前仪表盘的单位显示是否符合你的要求？计划后续将统一为那种形式。对于第二点，我认为还是显示出来比较好，否则刚开始用的人会看不懂，如果你有更好的想法请告诉我。此外，可以将你认为好看的截图分享到#24 我考虑在之后的说明文档中使用这些截图。

**Comment by xiaojianjian-huang** [comment]
您好，我是黄健。您的邮件我已收到，我会尽快处理的，谢谢。

**Comment by volatile-static** [comment]
beta版已经发布了，有条件的话可以试一下
https://github.com/volatile-static/Chartero/releases/tag/2.0.0-beta

**Comment by xiaojianjian-huang** [comment]
您好，我是黄健。您的邮件我已收到，我会尽快处理的，谢谢。
