### ISSUE TITLE
[Bug]与其他插件同时使用的冲突反馈

### ISSUE THREAD

**Issue by dcgggg** [volatile-static/Chartero#38]
开发者您好，在使用Chartero的过程中，我发现了一些bug。
已有使用者反馈，详见https://github.com/windingwind/zotero-pdf-translate/issues/401
在chartero开启的情况下，会出现[zotero-pdf-translate](https://github.com/windingwind/zotero-pdf-translate)，[zotero-reference](https://github.com/MuiseDestiny/zotero-reference)等插件的显示异常，开启多个pdf时，仅在第一个pdf右侧出现翻译或者参考文献table。

谢谢，期待您的回复

**Comment by dcgggg** [comment]
chartero版本号1.3.2与zotero版本号6.0.23-beta.5+bc07bf803

**Comment by dcgggg** [comment]
![图片](https://user-images.githubusercontent.com/87225817/226852382-e92bd602-60e0-4c94-b319-1ab2ad3e6ec7.png)
会出现bug的有还有这个Night插件，他们的开发者提出了这样的解决方案，以供参考

**Comment by volatile-static** [comment]
[Chartero.zip](https://github.com/volatile-static/Chartero/files/11046358/Chartero.zip)
试一下这个版本

**Comment by dcgggg** [comment]
bug已修复，感谢开发者！
