### ISSUE TITLE
一些bug反馈

### ISSUE THREAD

**Issue by MrLittleShark** [volatile-static/Chartero#39]
开发者好，这个插件中有些功能无法使用，比如范围，排序筛选等，日期范围的选择也有问题。
![image](https://user-images.githubusercontent.com/112299157/233617590-5b067a32-4690-4261-9d15-c5a57dc3d3ed.png)

**Comment by volatile-static** [comment]
是的，等Z7的新版本吧

**Comment by volatile-static** [comment]
https://github.com/volatile-static/Chartero/releases/tag/2.0.0-beta
