### ISSUE TITLE
右侧边栏会被仪表盘撑的很大

### ISSUE THREAD

**Issue by CherryWung** [volatile-static/Chartero#4]
仪表盘一栏会把右侧边栏撑的很大，很不方便![HE[`MTI%_7J_A3F8W)W[7_M.png](https://user-images.githubusercontent.com/29010852/196393079-b165b256-2b39-406f-bf44-8eb025e405dc.png)

**Comment by CherryWung** [comment]
你好，我的系统是win10专业版，版本号21H2，zotero版本是6.0.15。
改变窗口大小之后该问题依然存在，拉长右边栏时仪表盘会随之变长：




但是拉短右边栏时，仪表盘减小到一定程度之后就不继续减小了，把右边栏减到最小的话，仪表盘有一部分会被挡住：







&nbsp;




-  -  -  -  -  -  -  -  -  原来的  -  -  -  -  -  -  -  -  - 
来自：                                                                                                                         ***@***.***&gt;；
日期： &nbsp;2022 年 10 月 18 日星期二 06:33 PM
收件人： ***@***.***&gt;；
抄送： ***@***.******@***.***&gt;；
Subject:&nbsp;Re: [volatile-static/Chartero] 右侧边栏会被仪表盘撑的很大 (Issue #4)





 
你好，请问是什么操作系统？尝试改变窗口大小呢
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。Message ID: ***@***.***&gt;

**Comment by volatile-static** [comment]
以后会考虑修复的

**Comment by volatile-static** [comment]
目前看来没什么问题了，如果确定是Chartero的问题，可以重新打开这个issue
