### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by baileichao** [volatile-static/Chartero#40]
打开一篇博士论文，选择左侧的all images视图，点击最下面的加载更多图片的时候，加载到一定程度，论文剩下的图片就加载不出来了，而且会出现下图的对话框，并且无法消失。
![image](https://user-images.githubusercontent.com/57392772/236364602-e6bb6e0c-8167-4210-9754-e7ddbd4ffef3.png)

**Comment by volatile-static** [comment]
尽量不要用这个功能看扫描版文献，尤其是学位论文。

**Comment by volatile-static** [comment]
必要的话可以用这个代替：https://github.com/MuiseDestiny/zotero-figure
