### ISSUE TITLE
阅读记录条目的同步问题

### ISSUE THREAD

**Issue by coisini-95** [volatile-static/Chartero#41]
![图片](https://github.com/volatile-static/Chartero/assets/78250635/c01f357d-4825-4bed-9838-c1832603b774)
大佬您好，如图，同步阅读数据储存条目时报错，显示太长无法同步，这怎么解决呢，现用的版本是1.3.2

**Comment by volatile-static** [comment]
https://github.com/volatile-static/Chartero/issues/21#issuecomment-1433936481
等zotero7吧
