### ISSUE TITLE
阅读记录不能在不同设备上同步

### ISSUE THREAD

**Issue by douyh** [volatile-static/Chartero#42]
目前我在一台 mac 上和一台 PC 上分别安装了这个插件. zotero 通过坚果云同步. 但是我在 mac 上的阅读记录在 PC 上无法看到(包括进度条, 阅读时间等等); 在 PC 上的阅读记录在 mac 上也不能看到. 这个是目前插件不支持同步吗还是配置的问题?

**Comment by volatile-static** [comment]
你好，通常不会出现这种问题的。我没有试过mac与win同步，你能提供更具体的细节吗

**Comment by douyh** [comment]
我在 PC 和 mac 上都是使用坚果云进行同步的. Paper 下的内容都是可以同步的.
![image](https://github.com/volatile-static/Chartero/assets/34704737/9e4dd82a-e690-4d70-80e5-124a43b391c4)
我在"我的文库"的未分类条目中可以找到 chartero产生的 log,一共有 3 个文件(pc 和 mac 上都有三个文件).
![image](https://github.com/volatile-static/Chartero/assets/34704737/0fe54c74-a96f-47d6-9b3a-1695c652fb15)
但是这些文件的内容在 PC 和 mac 上不同.

**Comment by douyh** [comment]
比如在 mac 上的内容是这样
![image](https://github.com/volatile-static/Chartero/assets/34704737/b3ee8c2b-c010-4f8f-b8f2-cf75a6d7392c)
而在PC上的内容是这样
![image](https://github.com/volatile-static/Chartero/assets/34704737/c8029166-aac7-43cd-af83-4ab6455928c3)

**Comment by douyh** [comment]
我是否可以选择将 chartero 的 log 存放到某个固定的分类中, 比如在 paper/log 目录下,这样应该就能同步. 或者说是我的同步配置有什么问题?
![image](https://github.com/volatile-static/Chartero/assets/34704737/531a18af-e516-4696-9881-feb25a71ea44)

**Comment by douyh** [comment]
我没有手动设置条目为历史记录. 然后产生的三条 chartero 记录中分别有 1 条来自 mac(可以在 mac 上解析但是不能在 pc 上解析), 另外有一条来自 pc(可以在 pc 上解析但是不能在 mac 上解析), 还有一条来历不明. 我手动将 mac 和 pc 产生的记录 merge 到一起,然后删掉了多余的条目. 目前手动 merge ,并同时在两边设置该条目为历史记录之后, 阅读记录完成了同步.

**Comment by volatile-static** [comment]
如果没有其他问题，你可以关闭这个issue。
