### ISSUE TITLE
小Bug

### ISSUE THREAD

**Issue by sgh2696417956** [volatile-static/Chartero#43]
开发者好，我今天开始使用zotero7，并装了Chartero的2.0.0-dev版本，但是我在使用的过程中出现频繁报错的情况，报错内容为“请勿手动修改历史记录”，截图如下，而将Chartero插件关掉之后就不再报错，请问应该如何解决
![1690123094451](https://github.com/volatile-static/Chartero/assets/48831889/da8c62a2-acb5-4727-8b58-a748b1c209b5)

**Comment by volatile-static** [comment]
现在这个测试版还不能正常使用，建议等下个月更新
