### ISSUE TITLE
出现频繁的弹窗提示：请勿手动修改历史记录

### ISSUE THREAD

**Issue by Leaf12138** [volatile-static/Chartero#44]
如题，在Z7上使用2.0.0-dev版本插件，偶尔会频繁连续出现来自javascript Application的请勿修改历史记录的弹窗，关闭之后会继续连续出现，正常操作使用，未涉及手动修改历史记录]
![uTools_1690182201224](https://github.com/volatile-static/Chartero/assets/135523725/0848e5b3-c1f1-4490-a76c-e7fbbfaee7a3)

**Comment by volatile-static** [comment]
#43 重复了
