### ISSUE TITLE
无法显示文字

### ISSUE THREAD

**Issue by comppoo** [volatile-static/Chartero#45]
![image](https://github.com/volatile-static/Chartero/assets/91119897/46c2d4a3-a89f-49d7-8b5b-246d07f130b7)

开启后chatero及其它部分插件无法显示文字，禁用后其它插件恢复显示文字。

zotero 7.0.0-beta.32+5e27a7501 (64-bit)

**Comment by volatile-static** [comment]
麻烦你测试一下是哪个插件导致无法显示文字

**Comment by liut14** [comment]
我其他插件都禁用了，还是这样无法显示文字。版本同上。

**Comment by volatile-static** [comment]
你确定当前zotero设置的语言是简体中文吗

**Comment by jlu511** [comment]
> 感谢反馈，问题找到了，安装包已更新到原链接：https://github.com/volatile-static/Chartero/releases/tag/2.0.0-beta

404了

**Comment by volatile-static** [comment]
> Zotero 7 Beta 29 后 更新了 pdf viewer ,这里的显示图的图标也不见了 ![image](https://user-images.githubusercontent.com/91119897/259961999-350b9725-1898-4e84-a1dd-406e77f25e36.png)
> 
> https://forums.zotero.org/discussion/106716/available-for-beta-testing-updated-reader-with-epub-snapshot-support-and-new-annotation-types
> 
> The PDF code is here https://github.com/zotero/reader

这个问题比较复杂，而且也不是主要功能，等到下个版本再更新吧
