### ISSUE TITLE
您好，设置界面显示异常

### ISSUE THREAD

**Issue by yzy1228682367** [volatile-static/Chartero#46]
![CleanShot 2023-08-13 at 11 30 32@2x](https://github.com/volatile-static/Chartero/assets/50101175/0260e913-57b6-4adf-afc0-e9e2e989f497)

**Comment by volatile-static** [comment]
#45 确定是刚下载的吗

**Comment by yzy1228682367** [comment]
阿咦，从release重新安装一遍就正常了。
