### ISSUE TITLE
zotero 7.0 beta33 Bug

### ISSUE THREAD

**Issue by Saunak626** [volatile-static/Chartero#47]
在重复条目这一项中，右侧重复条目的窗口消失。
<img width="515" alt="image" src="https://github.com/volatile-static/Chartero/assets/34276206/08ba13e5-55cc-462d-8dd6-fd580379402c">

<img width="294" alt="image" src="https://github.com/volatile-static/Chartero/assets/34276206/834a1652-dd5d-42e5-af1e-022046460bb6">

**Comment by volatile-static** [comment]
按理来说这里不应该出现图表的对吧

**Comment by Saunak626** [comment]
> 按理来说这里不应该出现图表的对吧

是的，按理说应该是图1。但是开启插件就成了图2。
还有个问题想问下，这个阅读记录是每一个条目生成一个吗？
<img width="553" alt="image" src="https://github.com/volatile-static/Chartero/assets/34276206/bb60dea4-3ae8-4a0a-8d7c-14914e0ed343">

**Comment by volatile-static** [comment]
嗯我改一下重复条目的问题。这个记录应该是一个条目下面很多笔记的形式，不知道你这是怎么弄出来这么多空条目的？

**Comment by Saunak626** [comment]
> 嗯我改一下重复条目的问题。这个记录应该是一个条目下面很多笔记的形式，不知道你这是怎么弄出来这么多空条目的？

不清楚这个阅读历史记录是什么，双击就是跳转到github仓库

<img width="1519" alt="image" src="https://github.com/volatile-static/Chartero/assets/34276206/ac0c49ab-0f9a-43f6-af04-45a85a088fb2">

**Comment by volatile-static** [comment]
> > 嗯我改一下重复条目的问题。这个记录应该是一个条目下面很多笔记的形式，不知道你这是怎么弄出来这么多空条目的？
> 
> 不清楚这个阅读历史记录是什么，双击就是跳转到github仓库
> 

你看一下能不能全都删掉

**Comment by volatile-static** [comment]
与#49 的现象一样

**Comment by Geo123abc** [comment]
> 嗯我改一下重复条目的问题。这个记录应该是一个条目下面很多笔记的形式，不知道你这是怎么弄出来这么多空条目的？

V大，我的和他情况一样（windows10 64bit），
1. 我主库从zotero7 开始，每次 只要打开 chartero，随便点击几下条目，然后zotero就卡死了（需要资源管理器结束进程）；
2. 关闭chartero不会出现卡死的情况;

一直就没打开chartero，然后今天我想着是不是我文献库文献太多了（2w+），我就生成了一个只有几篇文献的新库，然后惊奇发现不会卡死了，但是发现了和这种相似的问题，就是“阅读历史记录”重复，具体表现如下（zotero7 beta38，扫描周期2秒）：
1. 打开zotero之后，随便阅读一篇文献，会生成一个“阅读历史记录”记录（姑且称为记录A），然后阅读其它文献，**也会在这个条目下生成多个子note（这和我之前在zotero中使用chartero记忆不太一样）**，就是chartero的记录；在关闭zotero之前，所有阅读记录都会在记录A中生成；
2. 重启zotero，打开一篇文献，然后会生成一个全新的“阅读历史记录”条目（姑且称为记录B），并且之前的阅读记录不在记录B里面，也就是此前的记录都是失效的，在关闭zotero之前，所有的阅读记录都在记录B里面；
3. 重启zotero，会类似步骤2，生成新的“阅读历史记录”

我尝试修改 “extensions.zotero.chartero.dataKey”的值，但是无效，还是每次重启zotero，生成新的“阅读历史记录”条目

是我有地方没正确设置导致的吗？

“Addon Item”应该是zotero style生成的记录

![](https://s3.bmp.ovh/imgs/2023/08/30/180bf28197287866.png)

**Comment by Geo123abc** [comment]
> > 嗯我改一下重复条目的问题。这个记录应该是一个条目下面很多笔记的形式，不知道你这是怎么弄出来这么多空条目的？
> 
> V大，我的和他情况一样（windows10 64bit），
> 
> 1. 我主库从zotero7 开始，每次 只要打开 chartero，随便点击几下条目，然后zotero就卡死了（需要资源管理器结束进程）；
> 2. 关闭chartero不会出现卡死的情况;
> 
> 一直就没打开chartero，然后今天我想着是不是我文献库文献太多了（2w+），我就生成了一个只有几篇文献的新库，然后惊奇发现不会卡死了，但是发现了和这种相似的问题，就是“阅读历史记录”重复，具体表现如下（zotero7 beta38，chartero v2.0.0 beta，扫描周期2秒）：
> 
> 1. 打开zotero之后，随便阅读一篇文献，会生成一个“阅读历史记录”记录（姑且称为记录A），然后阅读其它文献，**也会在这个条目下生成多个子note（这和我之前在zotero中使用chartero记忆不太一样）**，就是chartero的记录；在关闭zotero之前，所有阅读记录都会在记录A中生成；
> 2. 重启zotero，打开一篇文献，然后会生成一个全新的“阅读历史记录”条目（姑且称为记录B），并且之前的阅读记录不在记录B里面，也就是此前的记录都是失效的，在关闭zotero之前，所有的阅读记录都在记录B里面；
> 3. 重启zotero，会类似步骤2，生成新的“阅读历史记录”
> 
> 我尝试修改 “extensions.zotero.chartero.dataKey”的值，但是无效，还是每次重启zotero，生成新的“阅读历史记录”条目
> 
> 是我有地方没正确设置导致的吗？
> 
> “Addon Item”应该是zotero style生成的记录
> 
> ![](https://camo.githubusercontent.com/a6701c063b302e7fedd7da29422743ef5fc70a787b553bf7a63a479e32b10753/68747470733a2f2f73332e626d702e6f76682f696d67732f323032332f30382f33302f313830626632383139373238373836362e706e67)

文献太多可能会卡死zotero，建议为各个功能提供一个开关设置，类似“阅读器仪表盘实时刷新”这种设置，或者手动触发

**Comment by volatile-static** [comment]
@Geo123abc 非常感谢你提供如此详实的测试！
1. 根据你的情况，我限制了最大条目数量，现在超过100条时不会渲染侧边栏
2. 请安装[这个版本](https://github.com/volatile-static/Chartero/files/12475322/chartero.zip)，然后提交调试日志给我，谢谢
3. `dataKey`这个首选项已经弃用了，麻烦你手动删除它

**Comment by Geo123abc** [comment]
> @Geo123abc 非常感谢你提供如此详实的测试！
> 
> 1. 根据你的情况，我限制了最大条目数量，现在超过100条时不会渲染侧边栏
> 2. 请安装[这个版本](https://github.com/volatile-static/Chartero/files/12475322/chartero.zip)，然后提交调试日志给我，谢谢
> 3. `dataKey`这个首选项已经弃用了，麻烦你手动删除它

[日志](https://github.com/Geo123abc/tempfiles/blob/main/Debug.zip) 解压mm：#123zxc

**Comment by Geo123abc** [comment]
> #123zxc

[Debug-2](https://github.com/Geo123abc/tempfiles/blob/main/Debug-2.zip)

还是刚才那个密码

**Comment by Geo123abc** [comment]
> @Geo123abc 这次看起来很正常，还有什么问题吗？

这个问题还存在 
> 我主库从zotero7 开始，每次 只要打开 chartero，随便点击几下条目，然后zotero就卡死了（需要资源管理器结束进程）；

我本来想输出一次这样的日志，但是由于zotero卡死，无法导出，我再试试看看能不能导出

**Comment by Geo123abc** [comment]
> @Geo123abc 这次看起来很正常，还有什么问题吗？

[这是第三次debug](https://github.com/Geo123abc/tempfiles/blob/main/debug-3.zip) ，还是刚才那个密码
zotero 打开到关闭的日志，在zotero界面点选条目还是卡顿，中间有多次“无响应”（windows资源管理器看到的）。

**Comment by volatile-static** [comment]
记录还有问题吗

**Comment by Geo123abc** [comment]
> 记录还有问题吗

我也想看一下，但是基本上没法选择项目，稍微一动鼠标、点击一下zotero界面，然后就“无响应”，双击打开条目文件也是卡住了，这种情况下没法测试记录问题，日常使用时，我Chartero插件都不敢开。

这个卡顿是怎么回事啊？

**Comment by volatile-static** [comment]
> > 记录还有问题吗
> 
> 我也想看一下，但是基本上没法选择项目，稍微一动鼠标、点击一下zotero界面，然后就“无响应”，双击打开条目文件也是卡住了，这种情况下没法测试记录问题，日常使用时，我Chartero插件都不敢开。
> 
> 这个卡顿是怎么回事啊？

我文库比较小，卡顿的问题没有办法复现。你方便的话留个联系方式我远程看一下，或者我开个腾讯会议把链接发上来？

**Comment by Geo123abc** [comment]
> 

QQ992336802

**Comment by Geo123abc** [comment]
> > > 记录还有问题吗
> > 
> > 
> > 我也想看一下，但是基本上没法选择项目，稍微一动鼠标、点击一下zotero界面，然后就“无响应”，双击打开条目文件也是卡住了，这种情况下没法测试记录问题，日常使用时，我Chartero插件都不敢开。
> > 这个卡顿是怎么回事啊？
> 
> 我文库比较小，卡顿的问题没有办法复现。你方便的话留个联系方式我远程看一下，或者我开个腾讯会议把链接发上来？

QQ992336802
