### ISSUE TITLE
关于最新版 Chartero插件功能的bug与建议

### ISSUE THREAD

**Issue by 11good11** [volatile-static/Chartero#48]
感谢作者对这个插件做出了巨大的贡献，在最新版的插件中存在部分bug，主要是以下几个方面：
1. 仪表盘中阅读记录无法正常记录及显示（如图1）；
2. 作者气泡图/历史甘特图等均无任何信息（如图2）；

相关建议：
1. 筛选功能添加：在作者气泡图（甘特图，关键词饼图均可）中，如果点击相关作者（或者关键词）的气泡，便能将相关文章筛选出来，我想这功能真的是如虎添翼；
2. 作者气泡图存在的主要的问题是人名显示不全，有时候文献太多，人名也太多，往往显得很杂乱，建议采用柱状图形式来对文章所在的单位进行统计（横轴是相关实验室，纵轴为文章数量），相同研究方向的文章相关单位/实验室不会很多，这样柱状图便会很清晰，当点击该实验室的柱状图时，系统自动筛选出该实验室所有文章，同时软件界面右侧自动显示作者气泡图，再点击作者气泡图，又能进行一遍筛选。这样话，根据文件夹的文献，可以快速统计出哪些单位正在对该方向进行研究，研究程度如何等信息，不知道能否实现，感谢作者了！
![image](https://github.com/volatile-static/Chartero/assets/73817578/057a7de9-a7cc-44b3-8e4d-a84fb0f96a10)

![image](https://github.com/volatile-static/Chartero/assets/73817578/e903fd0e-976a-4414-bc84-e26d0f7a77b5)

**Comment by volatile-static** [comment]
感谢反馈！我有点不太理解，看你提出的两个建议非常好，应该是充分使用过后想到的，那为什么提到的bug却说这两个图没有显示呢？是不是部分文件夹有图而部分没有？请提供可以复现问题的步骤，谢谢。

**Comment by 11good11** [comment]
> 
是全都没有，不管是哪个文件夹，都没有作者气泡图。也不管是哪个文献，不管怎么读，仪表盘都没阅读记录😭

**Comment by volatile-static** [comment]
既然你从来没有见过气泡图的样子，那你提的这个建议有点莫名其妙了😂
看一下你“未分类条目”下有没有“阅读历史记录”

**Comment by 11good11** [comment]
未分类条目阅读记录，但是有两个，之前还能显示气泡的，阅读记录等都挺正常的，后面升级下zotero后，就出现了bug，我的zotero版本是zotero7-beta.33,插件版本是最新版的2.0.0-beta
![image](https://github.com/volatile-static/Chartero/assets/73817578/aabec27c-af70-4803-a187-d41af11463a5)

**Comment by 11good11** [comment]
今天升级后了软件后，发现之前的两个问题（仪表盘中阅读记录无法正常记录及显示；作者气泡图/历史甘特图等均无任何信息）突然又可以重新显示了，但是阅读记录记录的判别方式有问题，一篇16页文章都快读完了，却显示只读了一页，另外有的文件夹的气泡图可以显示了，但是有的文件夹的气泡图显示不了。

**Comment by volatile-static** [comment]
请问你是所有文档都只记录一页吗？如果是只有一篇文档不正常，那请你描述一下他有什么特别的地方

**Comment by 11good11** [comment]
> 

![image](https://github.com/volatile-static/Chartero/assets/73817578/9b77f60f-9c51-4e30-aeac-214d57c5a806)
只记录了其中一页，感觉这文献很正常，没啥特点，doi：https://doi.org/10.1016/j.ijhydene.2022.10.153

**Comment by volatile-static** [comment]
[chartero.zip](https://github.com/volatile-static/Chartero/files/12376626/chartero.zip)
我这边没有复现你的问题，麻烦你装上这个版本然后看一下调试输出的log

**Comment by 11good11** [comment]
> 

好的，谢谢了，麻烦您看下，重新看了一篇文章，也做了很多笔记，但阅读进度始终为0%
![image](https://github.com/volatile-static/Chartero/assets/73817578/8b4c9f0b-aacc-44d6-b271-4452e64f4630)

[Desktop.zip](https://github.com/volatile-static/Chartero/files/12384931/Desktop.zip)

**Comment by volatile-static** [comment]
看起来似乎是记录功能没有工作，你检查一下首选项里的扫描周期是不是1s？另外，压缩包可以编辑掉了

**Comment by llity** [comment]
哪里下载最新测试版呢？谢谢

**Comment by volatile-static** [comment]
> 哪里下载最新测试版呢？谢谢

https://github.com/volatile-static/Chartero/releases/tag/2.0.0-beta

**Comment by llity** [comment]
> > 哪里下载最新测试版呢？谢谢
> 
> [`2.0.0-beta` (release)](https://github.com/volatile-static/Chartero/releases/tag/2.0.0-beta)

偶尔开放下载吧

**Comment by volatile-static** [comment]
预览版总是在发布一段时间后自动隐藏，我也不知道怎么回事

**Comment by llity** [comment]
也不能自动更新新的预览版吗？不知道最近有没有更新哦

**Comment by volatile-static** [comment]
> 也不能自动更新新的预览版吗？不知道最近有没有更新哦

最近又发现了一批BUG……

**Comment by llity** [comment]
> > 也不能自动更新新的预览版吗？不知道最近有没有更新哦
> 
> 最近又发现了一批BUG……

加个自动更新预览版嘛。不知道哪里下载。。

**Comment by volatile-static** [comment]
怎么自动更新预览版啊

**Comment by volatile-static** [comment]
[chartero@2.0.0-beta.7.zip](https://github.com/volatile-static/Chartero/files/12836369/chartero%402.0.0-beta.7.zip)
你先试一下这个版本吧

**Comment by AnZhiJJ** [comment]
> [chartero@2.0.0-beta.7.zip](https://github.com/volatile-static/Chartero/files/12836369/chartero%402.0.0-beta.7.zip) 你先试一下这个版本吧

作者你好，为啥我能看到你的更新记录却看不到预发布里面的插件

**Comment by volatile-static** [comment]
2.1.0应该实现你的建议了
