### ISSUE TITLE
zotero 7.0 & macbook air m2 中chartero无法工作

### ISSUE THREAD

**Issue by ZZP-DMU** [volatile-static/Chartero#49]
**系统内核**：Darwin Macbook.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 arm64
**系统**：macOS Ventura 13.5
**zotero版本**: 7.0
**chartero版本**:[for zotero7-beta](https://github.com/volatile-static/Chartero/releases/tag/2.0.0-beta)
**问题描述**：仪表盘和菜单栏中的file栏功能均为空白
**重现方式**：打开软件就会发生，且在重启软件也无法解决
- 菜单栏中的file栏功能为空白，如下图
<img width="284" alt="Screenshot 2023-08-14 at 17 56 12" src="https://github.com/volatile-static/Chartero/assets/82870401/d312539c-ade6-46a2-b2e2-411315ffcb5c">

**Comment by ZZP-DMU** [comment]
并且它在macbook ari m2上，用zotero 6.0安装chartero for 6.0时，是能够正常工作的

**Comment by volatile-static** [comment]
你好，目前插件只支持中文使用，只在windows测试。苹果系统、英文版会稍晚支持

**Comment by ZZP-DMU** [comment]
好的，谢谢作者（大佬）！
