### ISSUE TITLE
大佬，请问下 7 版本的插件在哪里下载呀？感谢

### ISSUE THREAD

**Issue by Zhangxigu** [volatile-static/Chartero#52]

**Comment by volatile-static** [comment]
近几个版本还不太稳定，等过几天充分测试后再发布

**Comment by Zhangxigu** [comment]
真的很喜欢这个插件，希望能早日用上，感谢大佬！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: volatile-static ***@***.***&gt;
发送时间: 2023年9月2日 17:03
收件人: volatile-static/Chartero ***@***.***&gt;
抄送: Zhangxigu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [volatile-static/Chartero] 大佬，请问下 7 版本的插件在哪里下载呀？感谢 (Issue #52)





 
近几个版本还不太稳定，等过几天充分测试后再发布

**Comment by Echoiland** [comment]
真的很喜欢这个插件！希望epub也可以统计！感谢作者大大！

**Comment by volatile-static** [comment]
> 真的很喜欢这个插件！希望epub也可以统计！感谢作者大大！

当然可以，前两天刚写完

**Comment by baileichao** [comment]
现在下载下来在7里面安装，为什么还是提示无法与该版本的zotero兼容？

**Comment by volatile-static** [comment]
> 现在下载下来在7里面安装，为什么还是提示无法与该版本的zotero兼容？

现在兼容7的新版还没有正式发布，再等等吧

**Comment by volatile-static** [comment]
https://github.com/volatile-static/Chartero/releases/download/2.0.0-beta/chartero-beta.xpi
