### ISSUE TITLE
旧版本的记录突然就没有了，只剩下最新的三条了，这是什么原因呢？

### ISSUE THREAD

**Issue by baileichao** [volatile-static/Chartero#56]

**Comment by baileichao** [comment]
我用的一起是Zotero6，前面记录都是好的，但是某天打开，发现前面的记录都没有了，只有最近阅读的三条记录了，想问有可能恢复或者找回么？

**Comment by volatile-static** [comment]
回收站里没有的话就只能从上次自动备份的sqlite里查了。类似的issue很多你找一下看
