### ISSUE TITLE
Frequent error reporting

### ISSUE THREAD

**Issue by Pizeo** [volatile-static/Chartero#58]
![image](https://github.com/volatile-static/Chartero/assets/64719457/ea2a908a-0fc2-478b-9788-c58359eb9a3f)

**Comment by volatile-static** [comment]
What's your problem?

**Comment by Pizeo** [comment]
First of all, thank you for your contribution in making such an excellent plug-in. But after I installed it, every time I opened it, I was prompted that there were duplicates in the "reading history", as shown in the picture. 
![image](https://github.com/volatile-static/Chartero/assets/64719457/63e5cbd6-bb8b-48ab-9557-08132e9d6eb1)

**Comment by volatile-static** [comment]
Did them duplicates again after you merged them?

**Comment by Pizeo** [comment]
Yes

**Comment by Pizeo** [comment]
It still appears after closing the software and reopening it.

**Comment by Pizeo** [comment]
In addition, I noticed that issue #48 still exists.

**Comment by volatile-static** [comment]
> It still appears after closing the software and reopening it.

1. Disable the plugin `Chartero`
2. Merge the duplicate items
3. Restart Zotero
4. Enable `Chartero`

**Comment by volatile-static** [comment]
> In addition, I noticed that issue #48 still exists.

Please clearly indicate which specific issue is it.

**Comment by Pizeo** [comment]
> * Disable the plugin `Chartero`
> * Merge the duplicate items
> * Restart Zotero
> * Enable `Chartero`

Sorry， it does not work.

**Comment by Pizeo** [comment]
> > It still appears after closing the software and reopening it.
> 
> 1. Disable the plugin `Chartero`
> 2. Merge the duplicate items
> 3. Restart Zotero
> 4. Enable `Chartero`

When you switch the literatures, this bug will occur again.

**Comment by Pizeo** [comment]
> > In addition, I noticed that issue #48 still exists.
> 
> Please clearly indicate which specific issue is it.

![image](https://github.com/volatile-static/Chartero/assets/64719457/e502f17b-c48e-49d6-8337-6df644f6b7f2)
Reading has no record

**Comment by Pizeo** [comment]
‍It feels like a new reading record will be generated every time you read it, instead of continuing the original reading record.

**Comment by Pizeo** [comment]
If you operate on the same computer and read different documents each time, the record will increase as the number of operations increases.

**Comment by volatile-static** [comment]
- check your `scanPeriod` preference
- disable all other plugins and submit debug log here
