### ISSUE TITLE
关于同步记录丢失的一些问题和建议

### ISSUE THREAD

**Issue by douyh** [volatile-static/Chartero#59]
作者您好，非常喜欢chatero的这个插件。但是最近在使用中遇到了一些问题：当我有2台设备时，在A设备上阅读了论文，可以看到阅读记录。然后在B设备上打开zotero，但是并未关闭B设备上的zotero。第二天重新在A设备上打开zotero的时候，发现前一天在A设备上的阅读记录消失了，目前几次经验来看可能是因为我再B设备上打开了zotero未关闭导致的。

我的两台设备都是用的zotero6。

搜索了一下之前的一些issue，有看到之前有一位遇到了历史记录全部丢失，只剩下3个条目的问题。这个问题我在本月也遇到过一次。根据之前的相关讨论，我发现前面有关于每个记录放在一起还是单独放在某个item下面的讨论。

我有一些认为可能会有帮助的建议：
1. 支持log记录在一个指定的外部文件中，该文件通过连接的方式添加到zotero中，这样可以通过坚果云等服务对该log文件进行同步。
2. 每篇论文的阅读记录单独存放，避免不同设备同时读写同一个文件带来的conflict。

我不确定这个是否会对上述问题有帮助，非常感谢您的付出，希望chartero可以越做越好。

**Comment by volatile-static** [comment]
感谢你的建议，但是支持zotero6的版本不会再更新了，适用于Zotero7的新版本已经采用了“每篇单独存放”的形式。

**Comment by volatile-static** [comment]
当然可以，文档里有写
