### ISSUE TITLE
“侧边栏预览所有图片”功能：中文论文中“论文”二字会被识别为图片

### ISSUE THREAD

**Issue by Comte0825** [volatile-static/Chartero#6]
“侧边栏预览所有图片”功能：中文论文中“论文”二字会被识别为图片

**Comment by Comte0825** [comment]
期刊官网文件：http://shxyj.ajcass.org/Admin/UploadFile/Issue/202005130001/2022/7//20220717110821WU_FILE_0.pdf
知网附件下载地址：https://bar.cnki.net/bar/download/order?id=jBGETXBNdPImvx70aLAuJPYxPoFw%2Bp%2Bi0fIiSrcN6lUY8Hw7sEcvmtMIqGo20ve7k3PgOdB%2F8KZdF0hYj%2BY0tJ0PLIIoFLYwy5BgUEfsTywr4qya3J1MXVAeiRx5OlqslYPoaodMZpci4t%2BioHDgxUTYqpUji21c7P0tPvyc1oFJcaZEj%2B46E820A7h%2BQbx%2BgrFL2p3FiXltTMWgGoFPPkqSijTBrWF%2B3bcO72tYgJs%3D
知网链接：https://t.cnki.net/kcms/detail?v=IAiCDjVhe6fP8Qb2Cdghc9hdBcPC9EIF43ZAHhnrgjZUN7dF2h57dev_EU2bOzbKIO76S3t8U_7ytGWEJdUk8Yf4wOI3rqdWlwIbsD0Q4LHpNQlTurbvDsSi6Qjap76D&uniplatform=NZKPT

**Comment by GFDGIT** [comment]
我想加入最小宽度和高度限制会好一点吧。
如果能方便地将图片插到笔记那就更好了。

**Comment by GFDGIT** [comment]
> 我想加入最小宽度和高度限制会好一点吧。 如果能方便地将图片插到笔记那就更好了。
但另一方面，又觉得和笔记相关的功能，由better note插件实现是不是更好的方式？希望两位大佬多多合作了，非常感谢。

**Comment by volatile-static** [comment]
@GFDGIT 很好的建议。但我认为这种功能最好的归宿还是合并进zotero主线，而不是几个开发者来维护分散的插件

**Comment by volatile-static** [comment]
> 期刊官网文件：http://shxyj.ajcass.org/Admin/UploadFile/Issue/202005130001/2022/7//20220717110821WU_FILE_0.pdf
从这里下的文件是没问题的，并没有“论文”二字：
![image](https://user-images.githubusercontent.com/59945270/196857824-509e344e-e132-43dc-af4b-652f1c08eac9.png)
@Comte0825

**Comment by Comte0825** [comment]
> > 期刊官网文件：http://shxyj.ajcass.org/Admin/UploadFile/Issue/202005130001/2022/7//20220717110821WU_FILE_0.pdf
> 
> 从这里下的文件是没问题的，并没有“论文”二字： ![image](https://user-images.githubusercontent.com/59945270/196857824-509e344e-e132-43dc-af4b-652f1c08eac9.png) @Comte0825

但是我们一般插件下载都是直接知网的条目跟附件，期刊官网爬不到条目信息呜呜

**Comment by volatile-static** [comment]
@Comte0825 那应该去联系translator的开发者

**Comment by volatile-static** [comment]
> 我想加入最小宽度和高度限制会好一点吧。 如果能方便地将图片插到笔记那就更好了。

v1.2.1增加了以下三项限制：
1. 对于扫描版pdf只渲染前10页
2. 每页图片多于20张则跳过此页
3. 渲染总数限制
