### ISSUE TITLE
登录账号后，无法记录阅读记录，debug提示：[chartero]：记录被阻塞！

### ISSUE THREAD

**Issue by fneoc** [volatile-static/Chartero#60]
![提示记录被阻塞](https://github.com/volatile-static/Chartero/assets/59194656/92c8b597-2ad2-420e-b0a0-d00934257bcb)

**Comment by volatile-static** [comment]
尝试调大记录周期

**Comment by fneoc** [comment]
调成5s、10s，还是会这样

**Comment by volatile-static** [comment]
重启zotero后每次都这样吗？记录有保存成功过吗

**Comment by fneoc** [comment]
![_20231024141409](https://github.com/volatile-static/Chartero/assets/59194656/6bf92875-b9bb-4102-a299-0095c78fd0f4)
![_20231024143749](https://github.com/volatile-static/Chartero/assets/59194656/bfcf71e4-1922-4311-8391-1258d1cf4bf0)
上图不登录，没有同步数据时，是可以生成记录的。
下图登录后，会生成另一个阅读记录的项目，这个时候就不能记录了

**Comment by fneoc** [comment]
![_20231024144254](https://github.com/volatile-static/Chartero/assets/59194656/3c3d685a-45af-47fb-92de-fa1ce95f40f3)
![_20231024144310](https://github.com/volatile-static/Chartero/assets/59194656/ec16b067-4e00-4b41-a40f-54f837900c09)

上图不登录，没有同步数据时，是可以生成记录的。
下图登录后，会生成另一个阅读记录的项目，这个时候就不能记录了

**Comment by volatile-static** [comment]
你先登录账号，关掉其他插件然后”重启为启用日志模式“，把日志传上来

**Comment by fneoc** [comment]
> 你先登录账号，关掉其他插件然后”重启为启用日志模式“，把日志传上来

[Debug Output.txt](https://github.com/volatile-static/Chartero/files/13112201/Debug.Output.txt)

**Comment by volatile-static** [comment]
麻烦你在Error Console里运行一下`ZoteroPane.selectItem(532)`看看是哪个条目

> 日志可以删掉了

**Comment by fneoc** [comment]
> 麻烦你在Error Console里运行一下`ZoteroPane.selectItem(532)`看看是哪个条目
![_20231024162428](https://github.com/volatile-static/Chartero/assets/59194656/a60654ec-db1a-48b2-99a1-719649b6b984)

**Comment by volatile-static** [comment]
我这边没法复现你的问题，你可以安装测试版然后再看一下error console：https://github.com/volatile-static/Chartero/releases/tag/dev

**Comment by fneoc** [comment]
![_20231024172110](https://github.com/volatile-static/Chartero/assets/59194656/89737b3e-70c9-4823-973b-3a87eba39d09)
辛苦啦

**Comment by volatile-static** [comment]
请按如下步骤测试：
1. 关掉其他功能（比如小地图等）
2. 关闭chartero
3. 打开一个pdf标签页
4. 清空console
5. 打开chartero
6. console右上角筛选logs
7. 截图console
8. 点击打开的pdf
9. 截图console

**Comment by fneoc** [comment]
我找到问题所在了：
原因是我加入了一个共享群组，群组里的未分类中存在“阅读历史记录”项目，而我并未有修改文件权限，这个可能和我自己文库生成的生产了冲突。退出群组后，就可以正常生成记录了。附上群组，您开始进入看可不可以复现帮助debug，有相同问题可以退群组试试。
![_20231024185915](https://github.com/volatile-static/Chartero/assets/59194656/8d40a2f4-c3af-4e67-bfbf-562bac3caa29)
麻烦您了~

**Comment by volatile-static** [comment]
感谢！我已经复现了，过两天修复！
