### ISSUE TITLE
你好，未找到历史记录

### ISSUE THREAD

**Issue by AmaliaChiovv** [volatile-static/Chartero#61]
你好，装上7之后安装了该插件，在设置中点击自动搜索并导入旧版数据显示是没有的，如图所示。
![image](https://github.com/volatile-static/Chartero/assets/148880030/fdb791e5-9fe0-4b1e-9966-cf7b85067be5)
但是我想通过手动输入数据，是复制保存记录的笔记内容（如{"lib":1,"items":{"ULNVVVP6":{"n":12,"p":{"8":{"t":{"1693456077":10,"1693456087":10,"1693456097":10}}}}}}）到这个输入框吗？但是“导入黏贴的历史记录”始终是灰色的，点不动，我是小白，不太懂，球球指示。
![image](https://github.com/volatile-static/Chartero/assets/148880030/5b8ecc2d-18f2-4244-a091-9b1a122957ad)

**Comment by volatile-static** [comment]
粘贴进去之后就能点了

**Comment by AmaliaChiovv** [comment]
是复制这个【2H5K24WH {"readingTime":{"page":6,"data":{"0":20,"1":60,"2":200,"3":10}}}】吗
但是我复制了点不动呀，没有反应，没有弹窗 是输入了按键也是灰色的
![image](https://github.com/volatile-static/Chartero/assets/148880030/48a5f9c8-6209-44ee-938c-0b43f56c23cc)

谢谢您的回复Thanks♪(･ω･)ﾉ

**Comment by AmaliaChiovv** [comment]
目前我的“未分类条目”有这些数据，我不知道是用的哪些数据，还得麻烦您指明。
![image](https://github.com/volatile-static/Chartero/assets/148880030/a993f3bd-137e-4c1f-8ed0-44c185180bc9)

**Comment by volatile-static** [comment]
![image](https://github.com/volatile-static/Chartero/assets/59945270/cdf452dc-6508-43a1-9368-4967ba8ba6b7)
把这几个分别导入进去吧
- 按钮变灰确实是bug，马上修复

**Comment by AmaliaChiovv** [comment]
感谢！期待更新Thanks♪(･ω･)ﾉ
