### ISSUE TITLE
Zotero7版本下，阅读记录的生成是不是还是依赖于Chartero条目下的Json文件？

### ISSUE THREAD

**Issue by Pizeo** [volatile-static/Chartero#62]
我发现目前在没有这个条目时，新阅读的内容进度条不会变化。

**Comment by Pizeo** [comment]
好嘞，理解了。我也删除了原来的Chartero这个条目，发现是可以正常显示的。但是在连个设备之间同步时，一个设备数据视图正常的情况下，到另一个设备上，就无法正常显示了。包括进度条都不会更新了，而是会生成一个新的“阅读历史记录”重复条目。

**Comment by volatile-static** [comment]
或许你等同步完成后重启一下就好了

**Comment by Pizeo** [comment]
![image](https://github.com/volatile-static/Chartero/assets/64719457/4cb84dc0-b88e-487f-b952-d6c3f05f1328)
![image](https://github.com/volatile-static/Chartero/assets/64719457/ec1da928-57b4-4505-a9ef-94ed07283dc8)
![image](https://github.com/volatile-static/Chartero/assets/64719457/02cd2973-705f-4ff4-bbd8-276f6ff661fc)
![image](https://github.com/volatile-static/Chartero/assets/64719457/8e4b0d76-04d1-4693-82ec-23ff5acfaf78)
听从你的建议，重启之后啥都没有了。原来正常的那个，现在也变成这样了。

**Comment by Pizeo** [comment]
![image](https://github.com/volatile-static/Chartero/assets/64719457/4c7d1740-088a-4c25-8ec3-36607709a965)
下面这个空的是重启之后新生成的，也是它导致不正常显示的。这似乎是一个bug，每次重启都会出现。

**Comment by volatile-static** [comment]
关闭所有插件（包括chartero）然后合并重复条目，重启后只打开chartero

**Comment by Pizeo** [comment]
D1218190779
出现了新的Bug 
![image](https://github.com/volatile-static/Chartero/assets/64719457/89425efe-c631-4c3e-94d9-5573550ea409)
