### ISSUE TITLE
Open recent is empty

### ISSUE THREAD

**Issue by fkguo** [volatile-static/Chartero#64]
Hello,

Thank you for developing the nice add-on. 
Currently, the Reading Progress in the dashboard of the papers that I'm reading is always 0%, and the "Open recent" menu is empty. I fear that some settings need to be done for using it. Is there a more detailed description? 

Zotero version: 7.0.0-beta.47+f012a348a
Charter version: 2.1.1

**Comment by fkguo** [comment]
The problem was because the scan period was set somehow to 10000 seconds. After changing it to 1 second, it works. 
But now a problem is that in "Open recent", each pdf file appears 3 times.

Thanks.

**Comment by volatile-static** [comment]
Hi fkguo,
I’m glad you like it.
It seems that you are migrating from the legacy version, since it was using milliseconds for `scan period`. In that case, it is recommended using `auto import` in preferences pane. 
In _Mac OS_, menu items in `Open Recent` appear 3 times. This is a known issue.
