### ISSUE TITLE
作者关系图好像不对

### ISSUE THREAD

**Issue by baileichao** [volatile-static/Chartero#66]
我看信息栏生成的这个作者关系图好像是不对的，不知道这个生成 的机制是什么，里面好多明明不是通讯作者的，识别成了通讯作者，导致关系图很乱，并不是实际的情况，希望可以解决一下。

**Comment by volatile-static** [comment]
首先很感谢你反馈问题，但是你没有给出任何截图，我难道要虚空查错吗？
一作是调用的zotero提供的API，通讯是提取出作者列表的最后一个人。如果你发现实际情况不是这样，请给出证据；如果你认为这样识别不合理，请给出改进建议。
谢谢

**Comment by baileichao** [comment]
明白了，这个通讯提取的最后一个人啊，那就不好弄了，因为通讯可能是第一个作者后面的任意一个，不一定是第二个，也不一定是最后一个，看来确实是不好解决的问题。看来目前的这个关系图只能看看了，因为目前感觉也找不到好的方法真的识别出哪个作者是通讯作者。

**Comment by baileichao** [comment]
看来可能每个专业这个作者顺序还是有区别。手动调整顺序肯定是不行的，因为作者顺序是固定的，当我在写论文引用的时候，就按那个顺序来的，如果调整了，引用顺序就不对了。看来无解的问题了。

**Comment by volatile-static** [comment]
如果说通讯排名不固定是普遍情况的话，那我可能要砍掉这个功能了

**Comment by baileichao** [comment]
我是地理专业的，目前来看，我们专业的，通讯作者不一定是哪个，可能是第二个，最后一个，或者是一作后面的任意一个，无法确定的。
但是这个功能，我觉得可以给一个选项，就是我自己选择每篇论文的通讯是哪个人，反正只要选择了，插件能记忆住，也可以的，这样选择一次，保存到数据里面，以后也不用选择的。
还有一个小问题，就是Chartero保存数据的时候，能不能直接以附件的形式保存？而不是以笔记形式保存，因为目前用其它好个插件统计比如卡片的时候，一直会把Chartero的源数据识别为卡片。

**Comment by volatile-static** [comment]
我觉得每篇都自选的话不太现实，最好是提供一个全局选项，比如`2`代表二作是通讯、`-1`代表末位是通讯。
之前Zotero官方说要做类似的功能，所以我就一直没有实现，不过他们实现的太慢了，这个我也没办法。
你说的是zotcard吗？这种可以先通过patch之类的方法隐藏一下。

**Comment by baileichao** [comment]
这个他们官方确实得标示一下，后面好多插件实现起来相关功能也就方便了。

**Comment by xiaozuo1997** [comment]
作者关系图显示不全，大部分题目都不显示，比如我选中30个，只显示6-7个，如何解决，可以手动添加吗

**Comment by volatile-static** [comment]
> 作者关系图显示不全，大部分题目都不显示，比如我选中30个，只显示6-7个，如何解决，可以手动添加吗

目前是会排除只有一个作者的条目，不可以手动添加

**Comment by xiaozuo1997** [comment]
多个作者的也不显示，只有很少一部分会显示在作者图中



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月25日(周六) 上午10:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [volatile-static/Chartero] 作者关系图好像不对 (Issue #66)




  
作者关系图显示不全，大部分题目都不显示，比如我选中30个，只显示6-7个，如何解决，可以手动添加吗
  
目前是会排除只有一个作者的条目，不可以手动添加

**Comment by volatile-static** [comment]
@xiaozuo1997 你可以发几篇不显示的给我看一下吗

**Comment by xiaozuo1997** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月25日(周六) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [volatile-static/Chartero] 作者关系图好像不对 (Issue #66)




 
@xiaozuo1997 你可以发几篇不显示的给我看一下吗

**Comment by volatile-static** [comment]
@xiaozuo1997 你邮件的附件是不可以发到GitHub上来的。你不方便登录GitHub的话也可以去gitee上开issue

**Comment by xiaozuo1997** [comment]
![微信图片_20231126100520](https://github.com/volatile-static/Chartero/assets/147161775/49ed92e2-1921-4f8b-9409-7945c957e591)
![微信图片_20231126100526](https://github.com/volatile-static/Chartero/assets/147161775/d727ab44-c546-4f5c-832a-9664e07e64df)
![微信图片_20231126100530](https://github.com/volatile-static/Chartero/assets/147161775/aaf3f5ef-fec4-44b1-8e9e-c4c97c5de04c)
![微信图片_20231126100534](https://github.com/volatile-static/Chartero/assets/147161775/c44859c0-ab07-496e-b0da-5dfe2547f15d)

**Comment by volatile-static** [comment]
> 作者关系图显示不全，大部分题目都不显示，比如我选中30个，只显示6-7个，如何解决，可以手动添加吗

之前是因为没有阅读记录的不会显示，现在改了。

**Comment by xiaozuo1997** [comment]
有些有阅读的好像也不显示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月3日(周日) 下午4:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [volatile-static/Chartero] 作者关系图好像不对 (Issue #66)




  
作者关系图显示不全，大部分题目都不显示，比如我选中30个，只显示6-7个，如何解决，可以手动添加吗
  
之前是因为没有阅读记录的不会显示，现在改了。

**Comment by volatile-static** [comment]
> 有些有阅读的好像也不显示

请升级至2.2.2版本后再试一下

**Comment by baileichao** [comment]
目前首选项里面添加了一个功能，可以设置哪个位置是通讯作者，但是正如前讨论的一样，通讯作者有可能是一作后面的任何一个位置，并且每篇论文的位置都不一样，所以通过全局设置来实现识别通讯作者是不现实的，最起码在地理专业来看是这样子的，所以还是要添加每篇论文通过右键菜单手动选择哪个是通讯作者的功能。

**Comment by baileichao** [comment]
手动选择通讯作者的位置，诚然操作比较繁琐复杂，但是好处显而易见，只需要操作一样，通讯作者肯定是正确的，只要自动保存到记录里面，那永远是可以用。
