### ISSUE TITLE
MacOS 14.0 Ctrl点击无法跳转页面 

### ISSUE THREAD

**Issue by ititiy** [volatile-static/Chartero#67]
这个Ctrl+点击不能跳转到别的页面
<img width="335" alt="image" src="https://github.com/volatile-static/Chartero/assets/43445769/e39cc7f8-2db5-4680-8a36-0880f0bf4ef8">
<img width="365" alt="image" src="https://github.com/volatile-static/Chartero/assets/43445769/428f4cf3-9659-45d3-8bde-8335fa866586">
以及这个关联文献网跳转是需要进更多里边选择查看所选条目吗

**Comment by volatile-static** [comment]
1. 这个图你是所有文献都不能跳转吗？
2. 是的。

**Comment by ititiy** [comment]
是滴,所有都不跳转,尝试关闭其他插件只安装这一个还是不跳转,Ctrl和cmd都不跳转
