### ISSUE TITLE
Chartero导致zotero无法订阅RSS

### ISSUE THREAD

**Issue by GFDGIT** [volatile-static/Chartero#7]
安装了1.1.1版本，zotero订阅RSS时填入网址，不能识别标题，保存按钮变灰，禁用chartero后可以正常订阅。关闭其他所有插件，只启用chartero，仍然无法订阅。

**Comment by volatile-static** [comment]
感谢反馈，请问是否方便把出问题的rss链接发上来？

**Comment by GFDGIT** [comment]
> 感谢反馈，请问是否方便把出问题的rss链接发上来？

我试了好几个都不行，你可以试一下zotero论坛的RSS。
https://forums.zotero.org/comments/feed.rss

**Comment by volatile-static** [comment]
```
(3)(+0058591): FeedReader: Fetching feed from https://forums.zotero.org/comments/feed.rss

(3)(+0000002): TypeError: 'fetch' called on an object that does not implement interface Window. fetch@resource://zotero/pdf-reader/pdf.js:3673:48 Zotero.FeedReader@chrome://zotero/content/xpcom/feedReader.js:202:3 Zotero_Feed_Settings</this.validateURL<@chrome://zotero/content/feedSettings.js:116:29 oninput@chrome://zotero/content/feedSettings.xul:1:38 ZoteroPane</this.newFeedFromURL<@chrome://zotero/content/zoteroPane.js:1111:5 oncommand@chrome://zotero/content/standalone/standalone.xul:1:1

(3)(+0000000): FeedReader: Terminating feed reader (Processing failed)

(3)(+0000002): Error: Processing failed Error: Processing failed Zotero.FeedReader.prototype.terminate@chrome://zotero/content/xpcom/feedReader.js:233:32 Zotero.FeedReader/<@chrome://zotero/content/xpcom/feedReader.js:208:5 __webpack_modules__</notify/<@resource://zotero/pdf-reader/pdf.js:3489:16 flush@resource://zotero/pdf-reader/pdf.js:4003:5 From previous event: oncommand@chrome://zotero/content/standalone/standalone.xul:1:1
```
@windingwind 大佬看一下有什么思路吗？我仿照preview插件调用了pdfjs，不清楚怎么会影响到feed

**Comment by volatile-static** [comment]
可能与 #9 有关

**Comment by LiYimin-orz** [comment]
同样很关心这个问题，不知道大大什么时候可以解决这个问题

**Comment by volatile-static** [comment]
> 同样很关心这个问题，不知道大大什么时候可以解决这个问题

感谢关注。由于zotero本身的RSS代码写的不太好，这个问题目前较难解决。建议大家要用RSS的时候临时禁用chartero一下，谢谢
https://github.com/zotero/zotero/blob/af66712c77863a98a16324edc3b7d0c40371b3c4/chrome/content/zotero/xpcom/feedReader.js#L133-L138

**Comment by LiYimin-orz** [comment]
> 

感谢大大回复，决定不用RSS订阅啦，收藏期刊首页，自己开网页看最新和热门文章了

**Comment by LiYimin-orz** [comment]
> > 这个问题很有趣，不知道什么时候解决这个问题
> 
> 感谢关注。由于zotero本身的RSS代码写的不好的问题解决，目前较之问题。建议大家使用o的时候暂时禁止字符查看，谢谢
> 
> https://github.com/zotero/zotero/blob/af66712c77863a98a16324edc3b7d0c40371b3c4/chrome/content/zotero/xpcom/feedReader.js#L133-L138

感谢大大回复，决定不用RSS订阅啦，收藏期刊首页，自己开网页最新和热门文章了

**Comment by volatile-static** [comment]
@GFDGIT @LiYimin-orz 已修复
