### ISSUE TITLE
标签排除无法排除中文标签，待选项里面不显示中文标签

### ISSUE THREAD

**Issue by XinLi0111** [volatile-static/Chartero#74]
![image](https://github.com/volatile-static/Chartero/assets/31495943/905e49e5-6475-4709-82a5-b524759de451)

**Comment by volatile-static** [comment]
我这边搜索汉字是正常的。请问你安装的插件版本、zotero版本、操作系统版本？
麻烦你再添加一些中英混合的标签看能否搜到？

**Comment by XinLi0111** [comment]
中英混合的也搜不到。
插件版本 2.2.0
zotero: 7.0.0-beta.52+2f8e536f2 (64-bit)
系统：win11

**Comment by volatile-static** [comment]
你添加标签后，搜索框上面显示的标签总数有变化吗？
顺便，插件该升级了

**Comment by volatile-static** [comment]
哦，我知道了。这搜索框里只加载自动添加的标签，手动添加的不会显示。本来我想的是图中只画自动添加的标签，但现在看来似乎错误地把手动添加的也画上了
