### ISSUE TITLE
条目列表中出现多条《阅读历史记录》

### ISSUE THREAD

**Issue by wongtx** [volatile-static/Chartero#75]
如题如图
![image](https://github.com/volatile-static/Chartero/assets/46996862/41275279-da31-43c4-8cd9-8f1ad059a570)

**Comment by volatile-static** [comment]
或许是加了标签的原因，你把那些标签去掉然后重启同步几次试试

**Comment by wongtx** [comment]
> 或许是加了标签的原因，你把那些标签去掉然后重启同步几次试试

谢谢你的解答。您说的方法并没有奏效

**Comment by wongtx** [comment]
![image](https://github.com/volatile-static/Chartero/assets/46996862/eb867aea-e3aa-47fd-85d0-c55581177aac)
目前我发现插件并不能往条目中写数据每次都是空的，不知道是什么原因

**Comment by wongtx** [comment]
> ![image](https://private-user-images.githubusercontent.com/46996862/289279245-eb867aea-e3aa-47fd-85d0-c55581177aac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzU1MTcsIm5iZiI6MTcwMjEzNTIxNywicGF0aCI6Ii80Njk5Njg2Mi8yODkyNzkyNDUtZWI4NjdhZWEtZTNhYS00N2ZkLTg1ZDAtYzU1NTgxMTc3YWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE1MjAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYzI1YjEzNDNhY2RiMjA4YTFmODJmNmNmZWY4YTU3YmU0MWI4NDAyMjVhMWUyNDZhNWJlZmY1NGYzMTY0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rBxtXhbK0khSr1AqzOh8lKr4oac3DUf6EYlR1c7qU2w) 目前我发现插件并不能往条目中写数据每次都是空的，不知道是什么原因

我点了一下“清理记录数据”插件就又重新工作了

**Comment by volatile-static** [comment]
> 我点了一下“清理记录数据”插件就又重新工作了

挺好的，没有问题的话可以关闭issue了
