### ISSUE TITLE
“阅读历史记录”可以关闭吗？

### ISSUE THREAD

**Issue by horaynia** [volatile-static/Chartero#79]
“阅读历史记录”可以不让它产生吗？或者有没有开关选项，可以关闭这个。
<img width="156" alt="iShot_2023-12-18_21 54 20" src="https://github.com/volatile-static/Chartero/assets/50537627/00ee01ef-573f-4d47-bb67-689209ed2329">

**Comment by volatile-static** [comment]
你好，该功能是本插件的主要功能，所有图表的绘制均依赖历史记录。如果仅需阅读器侧边栏“所有图片”显示，可以考虑zotero-figure插件。

**Comment by horaynia** [comment]
佬，那可以生成“阅读历史记录”时，自动弄到一个新的生成文件夹里吗？而不是在所有文库里显示。

**Comment by volatile-static** [comment]
暂时不会做，因为在等zotero官方提供内置存储接口。你可以说一下为什么不想在文库显示吗

**Comment by horaynia** [comment]
会显得比较乱，而且它生成的位置也不固定，或者让他们在一个地方（最底部）集中显示也可以

**Comment by volatile-static** [comment]
> 会显得比较乱，而且它生成的位置也不固定，或者让他们在一个地方（最底部）集中显示也可以

怎么会不固定呢？不都是在同一个主条目下吗？跟style插件的存储方式是一样的
