### ISSUE TITLE
总阅读时长占比的显示问题

### ISSUE THREAD

**Issue by baileichao** [volatile-static/Chartero#80]
在文库总览的界面的总阅读时长占比这一项，点击某一个扇形图，会出来弹窗提示，比如下图，这个提示默认都是向上的，这个会挡住下面的扇形图的信息，不利用对照查看，是不是优化一下，点击下面的扇形图弹窗信息往下显示，点击右边的扇形图，则弹窗信息在右显示，这样的话，那个弹窗信息永远是在这个扇形统计图的外围，不会遮挡到扇形图。

![image](https://github.com/volatile-static/Chartero/assets/57392772/9c738276-6089-4f72-a714-2c27bc901c96)

**Comment by volatile-static** [comment]
这个不太好改
