### ISSUE TITLE
首页视图下甘特图显示可能有误

### ISSUE THREAD

**Issue by xiaojianjian-huang** [volatile-static/Chartero#84]
在二级文件夹仍然显示一级文件夹的统计信息
![微信截图_20240110115618](https://github.com/volatile-static/Chartero/assets/71034510/5521bd44-a528-4bd9-b5cb-cb02b89ef206)
<img width="929" alt="微信图片_20240110115757" src="https://github.com/volatile-static/Chartero/assets/71034510/dfe5a37a-cacd-4944-842e-54170e733b7c">

**Comment by volatile-static** [comment]
我怀疑是你二级目录下没有历史记录导致侧边栏没有刷新

**Comment by xiaojianjian-huang** [comment]
是的，测试了一下，阅读后会刷新！发现在没有阅读记录的任何目录转跳，甘特图不会更新。这样的话，能否改一下逻辑呢：当转跳到无阅读记录的目录，显示无阅读记录，谢谢~

**Comment by volatile-static** [comment]
感谢反馈
