### ISSUE TITLE
联动其他插件的小建议--统计html格式的时长建议

### ISSUE THREAD

**Issue by xiaojianjian-huang** [volatile-static/Chartero#86]
您好！最近zotero style插件推出全文翻译，生成html格式的翻译条目位于同一文献父目录下，似乎是由zotero内置阅读器打开，但似乎没有统计阅读html的时间，这个可以完善一下吗？
![Uploading 微信截图_20240113161500.png…]()

![Uploading 微信截图_20240113161710.png…]()

**Comment by xiaojianjian-huang** [comment]
![Uploading 微信截图_20240113161500.png…]()

**Comment by xiaojianjian-huang** [comment]
![微信截图_20240113161710](https://github.com/volatile-static/Chartero/assets/71034510/a8d24f31-c4a8-4652-85e5-a4f415b3d0c1)

**Comment by volatile-static** [comment]
html没有页码，不可以记录的
