### ISSUE TITLE
It freezes Zotero.app on startup on today's new version Chartero (on Zotero 7)

### ISSUE THREAD

**Issue by wzh4464** [volatile-static/Chartero#88]
What debug information should I provide? I disabled all others but Chartero and can still repeat the freezing. And when I disable Chartero the freeazing disappeared.

The freezing makes it impossible to copy output from the js console.

**Comment by wzh4464** [comment]
啊 可以说中文

**Comment by wzh4464** [comment]
总之就是出新版之后，一进入zotero就卡住，关闭其他插件只保留Chartero也是如此。关闭Chartero就没问题。卡住之后js控制台输出也无法向上滚动查看error.

**Comment by wzh4464** [comment]
renew: 空数据库新添加文件的话也不卡住 可能与历史信息不兼容?

**Comment by volatile-static** [comment]
感谢反馈，马上修复

**Comment by volatile-static** [comment]
@wzh4464 麻烦试一下2.3.3，没问题的话可以关闭issue了

**Comment by wzh4464** [comment]
收到 我试试

**Comment by wzh4464** [comment]
好了好了。哇效率真高！

**Comment by volatile-static** [comment]
惭愧，其实是之前的已知问题不小心发布出来了
