### ISSUE TITLE
仪表盘不见了

### ISSUE THREAD

**Issue by douyh** [volatile-static/Chartero#89]
今天突然zotero更新了一下，然后回来就找不到仪表盘了。在官网上看到了一个这样的信息https://forums.zotero.org/discussion/111074/available-for-beta-testing-zotero-redesigned
现在的右侧边栏就变了。一些其他插件原本在右侧的功能包括chartero的仪表盘都找不到了。
![image](https://github.com/volatile-static/Chartero/assets/34704737/a58907e8-9666-4b8a-b58c-4a66213cf1ed)

版本号是
![image](https://github.com/volatile-static/Chartero/assets/34704737/c09595b0-d312-4c22-a47e-92ed04cc8a1a)
7.0.0-beta.55+9151fb355 (64-bit)

请问一下这个是zotero更新引起的吗？

**Comment by volatile-static** [comment]
别急，他们更新都没给插件适配的时间

**Comment by ananzibian** [comment]
能退回原来的版本吗，感觉这个不好用啊

**Comment by volatile-static** [comment]
> 能退回原来的版本吗，感觉这个不好用啊

实在不习惯可以暂时先用着Z6，反正chartero1.x的数据可以迁移

**Comment by douyh** [comment]
> > 能退回原来的版本吗，感觉这个不好用啊
> 
> 实在不习惯可以暂时先用着Z6，反正chartero1.x的数据可以迁移

因为一些特殊的原因，我常用的PC上的软件卸载之后就没办法安装新的了。chartero做的非常好，新版本的适配只要在长期的计划中就好🫡

**Comment by volatile-static** [comment]
#90
