### ISSUE TITLE
Chartero安装后导致Mac版其他插件（Zotero IF Pro Max）的联网翻译功能失效

### ISSUE THREAD

**Issue by hxqiay** [volatile-static/Chartero#9]
您好，我在用Chartero的时候，感受到了Chartero插件十分美观，但同时我也遇到了一个问题：在安装Chartero后我Mac版的Zotero IF Pro Max插件的翻译功能显示无法连接服务器（如下图所示），但Windows版的依然可以翻译，请问是什么状况？后我又卸载了Chartero插件，翻译功能又可以用了。
<img width="229" alt="截屏2022-10-22 12 41 24" src="https://user-images.githubusercontent.com/106989292/197320131-0dec9801-4b8e-459c-aaeb-ace38f38163b.png">
<img width="323" alt="截屏2022-10-22 12 41 42" src="https://user-images.githubusercontent.com/106989292/197320133-d34ce825-a28f-4867-939a-461e7ec58fa8.png">

**Comment by volatile-static** [comment]
您好，感谢您的鼓励。IF Pro Max属于商业软件，我们开源开发者没办法对与其相关的任何bug进行定位及测试。相关问题请联系青柠学术

**Comment by volatile-static** [comment]
@hxqiay 已修复
