### ISSUE TITLE
阅读进度显示在侧栏

### ISSUE THREAD

**Issue by Skylar-Shao** [volatile-static/Chartero#90]
<img width="1279" alt="image" src="https://github.com/volatile-static/Chartero/assets/133140235/9528dfbe-61b5-499b-bed4-488533c6dbe4">
已经安装最新版本2.3.3的插件，但阅读进度显示在侧栏笔记中，找我自己的笔记很不方便。请问是zotero更新的问题吗？不知道作者什么时候有时间更新，谢谢回答！

**Comment by volatile-static** [comment]
更新beta55后大部分功能瘫痪，等这两天发布一个阉割版解决兼容问题，完整版要等zotero官方提供相应的接口（遥遥无期）

**Comment by YYde123** [comment]
新版UI很不习惯，这个对插件开发使用也太不友好了

**Comment by Skylar-Shao** [comment]
> 更新beta55后大部分功能瘫痪，等这两天发布一个阉割版解决兼容问题，完整版要等zotero官方提供相应的接口（遥遥无期）

辛苦了！谢谢！（今天一早上醒来，打开Zotero发现变天了，吓死了

**Comment by volatile-static** [comment]
阉割版已发布
