### ISSUE TITLE
最新zotero7右侧查看栏与chartero适配

### ISSUE THREAD

**Issue by hzp2333** [volatile-static/Chartero#91]
感谢您的开发！年度总结和仪表器记录都促使我阅读文献更加勤奋。
昨天zotero7更新后似乎出现了一些适配问题，新的zotero7界面精简了查看栏，因此chartero的查看栏似乎消失了。请问大佬还有做适配的计划吗？
再次感谢您的项目！
![3835bc63efece05b1c6f4050e32dfe3](https://github.com/volatile-static/Chartero/assets/79459902/a8d58a1b-1455-42f5-b189-533b6a9b1d6b)

**Comment by volatile-static** [comment]
#90
