### ISSUE TITLE
crashed when launch Zotero 启动 Zotero 就会无响应

### ISSUE THREAD

**Issue by DavidJoyDong** [volatile-static/Chartero#92]
暂时不知道是偶然的 bug 还是必然的 bug

### 环境
macOS 14.2.1
Zotero 7 beta54
Zotero 7 beta55

### 情景
只要我打开 Zotero，大概在加载插件阶段就会卡死，只能强制退出。

### 触发方式&复现方式描述
这个我暂时没办法准确复现
当时正好还赶上 Zotero 7 beta 54 -> 55 的自动更新了。
我当时往库里拖拽添加了几个 pdf，然后就卡死了。
重启后就变成了 beta 55 的介面，启动后就卡死。
重新安装回了 beta 54 启动依然卡死。

崩溃时，我是选中的一个收藏夹，右侧栏有本插件的图表，没渲染出来。

### 解决
- 去 profile 处 https://www.zotero.org/support/kb/profile_directory
- 把此插件的 .xpi 文件删除
- 把 `extensions.json` 中此插件相关代码删除
再启动 Zotero 就正常了

排查了好几个插件最后确定是删除此插件可以正常进入软件。

**Comment by volatile-static** [comment]
2.3.2版本确实会卡死，升级一下就好了

**Comment by DavidJoyDong** [comment]
> 2.3.2版本确实会卡死，升级一下就好了

好的，不过可能我遇到的情况比较特殊。

打开软件即卡死 -> 无法正常通过 GUI 更新 -> 用特殊方法先删除此插件 -> 打开软件 -> 安装新版

给其他人一个参考吧。

**Comment by volatile-static** [comment]
很抱歉给大家造成如此严重的困扰
