### ISSUE TITLE
最近打开/关闭的历史很有用，希望在工具栏或者标题栏增加打开按钮

### ISSUE THREAD

**Issue by llity** [volatile-static/Chartero#95]
最近的历史中需要去除重复打开或关闭的条目。类似下面这个
![image](https://github.com/volatile-static/Chartero/assets/11771112/d91e0fa0-a4f5-4646-8c0d-971d0d40d21c)

**Comment by volatile-static** [comment]
没太理解你的意思，是想说 #54 这个问题吗

**Comment by llity** [comment]
是的，在加一个历史关闭的按钮到标题栏，方便打开之前关闭的PDF，已经打开的PDF排除在外

**Comment by volatile-static** [comment]
实现了，你可以先用dev版看看

**Comment by llity** [comment]
谢谢
