### ISSUE TITLE
2.5.0版本减少的功能

### ISSUE THREAD

**Issue by yunmiumiu** [volatile-static/Chartero#98]
更新到2.5.0之后不显示minimap、阅读期间的挂机提醒和单个条目的仪表盘了，不知道是bug还是取消了这些功能。
另外目前只有在选择Library里的某个文件夹的时候，相关选项才会出现在侧栏中。
还想问下除了timeline以外的功能，如标题云图，是否无法识别中文文本？

**Comment by volatile-static** [comment]
#81 #90 是的

**Comment by yunmiumiu** [comment]
感谢回复，我退回旧版使用好了。希望官方能尽快给接口。
