### ISSUE TITLE
作者关系图显示问题

### ISSUE THREAD

**Issue by baileichao** [volatile-static/Chartero#99]
发现作者关系图里面显示的只是当前选择目录下的文献，比如我的文库文件夹下面有几个子目录，则这些子目录的文献不会显示，这个感觉在使用的时候不太友好，因为有时候同几个作者的论文，可能放在一个大的父文件夹下的几个子文件夹里面，如果想看整体的作者关系之类的，就没法子显示了。

**Comment by volatile-static** [comment]
![image](https://github.com/volatile-static/Chartero/assets/59945270/60379c74-7cfd-4bb3-863a-18419007bd12)
zotero本身就可以设置显示子分类的
